# -*- coding: utf-8 -*-
"""Tier 2 hub + six city x service pages for Dundee, FL (Polk County). Researched September 2026:
Town of Dundee's own Development Services (Building) Department and Public Works & Utilities pages,
the SWFWMD Modified Phase III extension, Polk County Water Atlas lake records, the Dundee depot's
railroad history, GrowthSpotter's Woodland Ranch Estates coverage, Census QuickFacts and the USDA
Candler series description already used for the Polk County ridge in c_counties.py."""
from _data import CITIES
from _helpers import page, capsule, sec, table, faq, a, svc, city, post, src, ext, price
from _cityservice import cityservice_pages

SLUG = "dundee"
C = CITIES[SLUG]

DUNDEE_BUILDING = ("Town of Dundee — Development Services (Building) Department", "https://townofdundee.com/departments/building-services/")
DUNDEE_UTIL = ("Town of Dundee — Public Works & Utilities", "https://townofdundee.com/departments/public-works-utilities/")
SWFWMD_EXT = ("Southwest Florida Water Management District — district extends Modified Phase III water shortage order", "https://www.swfwmd.state.fl.us/the-newsroom/2026/district-extends-modified-phase-iii-water-shortage")
POLK_PA = ("Polk County Property Appraiser — parcel search", "https://www.polkflpa.gov/")
CANDLER_OSD = ("USDA NRCS — official series description, Candler series", "https://soilseries.sc.egov.usda.gov/OSD_Docs/C/CANDLER.html")
LAKE_MARIE = ("Polk County Water Atlas — Lake Marie (Dundee)", "https://polk.wateratlas.usf.edu/waterbodies/lakes/160635/lake-marie-dundee")
LAKE_MENZIE = ("Polk County Water Atlas — Lake Menzie", "https://polk.wateratlas.usf.edu/waterbodies/lakes/160646/lake-menzie")
LAKE_ANNIE = ("Polk County Water Atlas — Lake Annie", "https://polk.wateratlas.usf.edu/waterbodies/lakes/160723/lake-annie")
DEPOT_MARKER = ("Historical Marker Database — “The Railroad in Dundee” history marker", "https://www.hmdb.org/m.asp?m=93192")
DEPOT_MUSEUM = ("Town of Dundee — Margaret Kampsen Historic Depot", "https://townofdundee.com/departments/cultural-affairs/margaret-kampsen-historic-depot/")
WOODLAND_RANCH = ("GrowthSpotter — Holiday Builders takes position in Dundee's Woodland Ranch Estates", "https://www.growthspotter.com/2025/06/12/holiday-builders-takes-position-in-dundees-woodland-ranch-estates/")
CENSUS_DUNDEE = ("U.S. Census Bureau — QuickFacts, Dundee town, Florida", "https://www.census.gov/quickfacts/fact/table/dundeetownflorida/PST120225")

SRC = [DUNDEE_BUILDING, DUNDEE_UTIL, SWFWMD_EXT, POLK_PA, CANDLER_OSD, LAKE_MARIE, LAKE_MENZIE, LAKE_ANNIE,
       DEPOT_MARKER, DEPOT_MUSEUM, WOODLAND_RANCH, CENSUS_DUNDEE, "dep-rule", "fs125572"]

# ============================================================== hub
HUB = page(
    C["route"], "city",
    "Artificial Turf in Dundee, FL (2026)",
    f"Synthetic turf installation in Dundee, FL: the town's own permit office, Candler ridge sand, three named lakes and the {price('residential')} market range, checked September 2026.",
    "Artificial turf on Dundee's ridge, from the depot to the new subdivisions",
    capsule(f"Kissimmee Artificial Turf installs synthetic lawns, pet turf and putting greens in Dundee, the citrus-and-rail town on US-27 about {C['miles']} miles from our Kissimmee base, at the same {price('residential')} range as the rest of Central Florida. Dundee runs its own Development Services Department for building permits, separate from Polk County's office. As of September 2026, the town's own water utility answers to the district's Modified Phase III shortage order."),
    "".join([
        sec("A depot town on the ridge, not a subdivision suburb",
            f"<p>Dundee was named in 1910 after a settler's hometown in Scotland, and the Atlantic Coast Line Railroad's arrival the following year, on its new Haines City-to-Sebring branch, turned a citrus crossroads into a town almost overnight ({ext(DEPOT_MARKER[1], 'a historical marker on the depot grounds')} covers the full account). The 1912 depot on Main Street, the first stop built on that branch line, still stands today as the {ext(DEPOT_MUSEUM[1], 'Margaret Kampsen Historic Depot Museum')}, and the packing house the Dundee Citrus Growers Association built beside the tracks in 1929 is a reminder that fruit, not rooftops, built this town first. The 2020 Census counted 5,235 residents ({ext(CENSUS_DUNDEE[1], 'Census Bureau figures')}), a scale small enough that a single town office, not a county building complex, still handles the paperwork.</p>"),
        sec("The lakes that set Dundee's turf setback",
            f"<p>Dundee counts eight lakes within town limits, four of them open to the public, and three come up often on a turf job: 32-acre Lake Marie, next to the community center's own park and playground on Main Street; 21-acre Lake Menzie; and 407-acre Lake Annie, bordered on its east side by the Barbara B. Pedersen Wildlife Preserve ({ext(LAKE_MARIE[1], 'Polk County Water Atlas records')}). Florida's May 19, 2026 turf standard draws a 10-foot line around all three: no synthetic grass closer to the water than that, except behind an existing seawall or bulkhead, and none at all inside a drainage swale or a pond's own littoral zone ({src('dep-rule', 'Rule 62-308.100')}). A lakefront lot on any of Dundee's public lakes usually has more usable yard than that line first suggests; it just isn't the strip closest to the shoreline.</p>"),
        sec("New subdivisions on graded ridge lots",
            f"<p>South of {city('haines-city', 'Haines City')}, Holiday Builders and DRB Homes are building Woodland Ranch Estates, a 116-acre subdivision on old grove land with homes priced from the high $200s ({ext(WOODLAND_RANCH[1], "GrowthSpotter's coverage of the project")}). The native ground under that grading is Candler sand, excessively drained and rated very rapid to rapid in permeability, built from thick wind-blown and marine deposits with slopes that can run up to 12 percent on the ridge ({ext(CANDLER_OSD[1], "the USDA's official series description")}). Fast-draining sand keeps a yard from pooling, but it also shifts more than the heavier soils to the south, which is why a base on a sloped Dundee lot gets compacted in careful lifts and every edge gets anchored against sliding, since the state rule's ban on infill washing off the property is a practical concern here, not just a paperwork line.</p>"),
        table("Dundee yard types and what we do differently",
              ["Yard type", "What's different", "What we do"],
              [["Lakefront lot on Marie, Menzie or Annie", "Closer than 10 feet to the shoreline is off-limits, a seawall or bulkhead being the one exception", "Stake the setback line first, then measure the buildable turf area against it"],
               ["New Woodland Ranch Estates lot", "Builder-graded ridge fill over Candler sand, thin sod barely rooted", "Full base rebuild in washed rock rather than turf laid over what's there"],
               ["Older in-town lot near Main Street", "Narrow platted lots from the citrus-rail era, mature shade trees", "Drip-line check before any digging, tighter access planning for equipment"],
               ["Ridge-slope backyard off US-27", "Loose, fast-draining Candler sand on real grade change", "Extra compaction lifts and a firmer edge anchor against sliding infill"]],
              "Compiled from Polk County Water Atlas lake records, USDA's Candler series description and Woodland Ranch Estates' own site plan, checked September 2026."),
        sec("Who reviews a turf permit in Dundee",
            f"<p>The Town of Dundee runs its own Development Services Department rather than routing permits through Polk County or a contracted plan-review firm, which puts it in different territory from several of the small towns around it. The office, at 124 Dundee Road, takes applications by downloaded form emailed to permits@townofdundee.com or a call to (863) 438-8330 ({ext(DUNDEE_BUILDING[1], 'Development Services')}). As of September 2026 its published permit list doesn't name synthetic turf specifically, so a straightforward lawn conversion is worth a call before scheduling a crew. {a('/laws/permits/polk-county/', 'Our Polk County permit page')} covers the state rule and the county's own building division for context, but it's Dundee's own office, not the county's, that actually reviews an application inside town limits. Running a Dundee-area address through {ext(POLK_PA[1], "a parcel lookup on the county property appraiser's site")} settles whether it's inside town limits or unincorporated county before either call, and {a('/laws/hoa-rules/', 'a Dundee HOA, where one exists')} still answers to the separate visibility statute covered on our HOA page, not the town's own permit process.</p>"),
        "<!--AUTO:city-services-->",
    ]),
    faqs=[
        faq("What should the best artificial grass installer near me in Dundee already know about ridge lots?", "Whether they've priced a Dundee job before: specifically, whether they know the town issues its own permits instead of Polk County, and whether they'll stake a 10-ft setback on a lake lot before ordering material. An installer who mentions the ridge sand's drainage without being asked has actually looked at the address."),
        faq("Does the Town of Dundee or Polk County issue the permit for a backyard turf project?", "Dundee's own Development Services Department does, at 124 Dundee Road, since the town runs its own building office rather than sending applications to the county. Our Polk County permit page still covers the state rule that applies inside Dundee, even though the county isn't who opens the file."),
        faq("How many lakes does Dundee have, and does that change a turf project?", "Eight lakes sit inside town limits, four of them open to the public. Lake Marie, Lake Menzie and Lake Annie come up most often on a residential job, and building within 10 feet of any of the three needs a seawall or bulkhead already standing in for the state's buffer."),
        faq("What's the current watering schedule for Dundee's own water utility?", "Dundee's addresses are down to one irrigation night a week under the Southwest Florida district's extreme-shortage order, even numbers on Tuesday and odd on Thursday, before 4 a.m. or after 8 p.m., a restriction the district extended through October 1, 2026. A capped synthetic lawn skips that schedule entirely."),
        faq("Does new construction near Woodland Ranch Estates need a different turf base than an older Dundee lot?", "The material is the same washed crushed rock either way, but a new-construction lot usually needs the builder's compacted grading broken up first, while an older in-town lot's undisturbed Candler sand mostly just needs shaping and compaction in proper lifts."),
    ],
    sources=SRC, city=SLUG, crumbs=[("Service areas", "/areas/")], crumb="Dundee",
    related=[("/areas/polk-county/", "Artificial turf across Polk County"), ("/laws/permits/polk-county/", "Polk County permit rules for turf"),
             ("/areas/haines-city/", "Turf in Haines City"), ("/areas/winter-haven/", "Turf in Winter Haven"), ("/artificial-turf-cost/", "Turf cost tables for Central Florida")])

# ============================================================== local
LOCAL = {
    "residential": {
        "title": "Artificial Grass Installation in Dundee, FL – Ridge Lots",
        "meta": f"Synthetic lawn installation in Dundee, FL: Candler ridge sand, US-27 subdivision growth, town-run permits and the {price('residential')} market range, September 2026.",
        "h1": "Dundee Artificial Grass: Built for Ridge Sand and Lake Lots",
        "lede": capsule(f"Artificial grass installed in Dundee runs {price('residential')} a square foot as of September 2026, the same Central Florida range whether the lot backs onto Lake Annie or sits on a graded corner of Woodland Ranch Estates. Dundee's excessively drained Candler ridge sand changes the base more than the turf itself, and the town's own Development Services Department, not Polk County, reviews the permit."),
        "sections": [
            ("Why Woodland Ranch Estates lots need more base than the turf alone",
             f"<p>Woodland Ranch Estates, the 116-acre subdivision Holiday Builders and DRB Homes are building south of {city('haines-city', 'Haines City')} on old grove land, is the clearest example of what a graded lot does to a lawn in Dundee. A pad site gets cut and filled to grade before a house ever goes up, which compacts the native Candler sand hard enough that builder sod often struggles within its first year, thin roots sitting on a crust the original ridge sand never had. Converting that same lot to turf doesn't inherit the problem, because the build starts by breaking up that compacted pad and replacing it with two to four inches of washed, open-graded crushed rock in its own right, not by laying turf over whatever grade the builder left. A newer Dundee lot and a decades-old one end up needing the same base for opposite reasons: one because the sand was disturbed too much, the other because it was never shaped at all.</p>"),
            ("Older lots near Main Street and the depot",
             "<p>The blocks around Dundee's Main Street and the 1912 depot were platted when the Atlantic Coast Line's Haines City-to-Sebring branch first brought settlers through, and the lots there run narrower than anything a modern subdivision plat allows, often with a live oak or two planted decades before the turf rule existed. Florida's May 2026 turf standard keeps synthetic grass out of any tree's drip line, on the property it sits on or next door, unless a certified arborist signs off, and a narrow in-town lot makes that line matter more than it would on a half-acre ridge parcel with room to spare. Access is the other in-town wrinkle: a gate barely wide enough for a wheelbarrow, common on these older lots, changes how base material gets moved in more than it changes what goes into the ground.</p>"),
            ("Getting a straight answer from Dundee's own permit office",
             f"<p>Because Dundee runs its own Development Services Department at 124 Dundee Road rather than sending applications to Polk County, a call to (863) 438-8330 gets a direct answer instead of a countywide phone tree. As of September 2026 the department hasn't published a line item for synthetic turf specifically, which puts a Dundee homeowner in the same position as most of the region: {a('/laws/florida-hb-683/', "the state's May 2026 rule")} sets the material and setback floor, and the town's ordinary building and drainage review still applies on top of it. {a('/laws/permits/polk-county/', 'Our Polk County permit page')} walks through that state layer in more depth, even though it's Dundee's own office, not the county's, that opens the actual file.</p>"),
        ],
        "scenario": ("Say you have a 640 sq ft backyard off Dundee Highway",
                     f"<p>Say a 1970s ranch house a few blocks off Dundee Highway has a 640 sq ft backyard, mostly bare dirt after a summer of trying to keep St. Augustine alive on Candler sand that drains almost as fast as it's watered. At {price('residential')} a square foot, that yard lands between roughly $5,120 and $11,520 installed, with the final number depending on how much old irrigation has to be capped and how far a crew has to hand-carry base material through a side gate. A lot backing onto Lake Menzie a few streets over prices the same way per square foot; what changes there is staking the state's 10-ft setback before ordering material, not the rate itself.</p>"),
        "faqs": [
            faq("Does turf near Lake Marie's community park need to sit back from the water?", "Yes, the same as any Dundee lake. Florida's rule holds turf 10 feet off Lake Marie, Menzie or Annie's ordinary shoreline, closer only where a seawall already does that job, and bars it from a drainage swale entirely. A lot near the community center's park on Main Street still has plenty of usable yard outside that strip."),
            faq("Does a new Woodland Ranch Estates lot need a different base than an older Dundee house?", "The washed rock is identical either way, but a new-construction lot usually needs the builder's compacted grading broken up first, while an older in-town lot's undisturbed Candler sand mostly just needs shaping. Skipping that step on a new lot is the more common reason a base fails early."),
        ],
        "sources": SRC,
    },
    "pet": {
        "title": "Pet Turf & Dog Runs in Dundee, FL – Ridge Sand Yards",
        "meta": f"Pet turf and dog runs in Dundee, FL: capped irrigation on well-drained Candler sand, the {price('pet')} market range and the town's own permit office, September 2026.",
        "h1": "Dog-Run Turf for Dundee's Ridge Lots and In-Town Yards",
        "lede": capsule(f"A dog run in Dundee costs {price('pet')} a square foot installed, the Central Florida range that holds whether the run sits on a half-acre Woodland Ranch Estates lot or a fenced strip behind an older Main Street bungalow. Dundee's fast-draining Candler sand already handles urine better than the heavier soils inland, and the town's own Development Services Department, not Polk County, still reviews the permit."),
        "sections": [
            ("Why Candler sand is a head start for a dog run",
             f"<p>Dundee's native ground is Candler fine sand, excessively drained and rated very rapid to rapid in permeability by the USDA's own series description, which means a dog run here starts with less of a fight against standing urine than a run built on the flatwoods soils around Kissimmee ({ext(CANDLER_OSD[1], "USDA's Candler series description")}). That head start is in the native soil, not the finished lawn: the washed, open-graded rock base and the infill choice, silica or zeolite rather than anything synthetic, still do the actual odor work, and a weed barrier still gets skipped under a pet area even on the driest Dundee lot, since fabric traps liquid at the surface instead of letting the fast sand underneath carry it away.</p>"),
            ("Capping a well or city-fed sprinkler zone the same way",
             "<p>A dog run's sprinkler zone gets capped at the valve box before turf goes down, and that step doesn't care whether the water behind it came from Dundee's own public utility or, on a handful of older outlying parcels, a private well: Florida's turf rule bars an in-ground system from watering synthetic turf either way. Dundee's Public Works & Utilities Department has been expanding its own wastewater collection system in recent years, a separate project from anything a pet-turf install touches, but it's a reminder that the town runs its own utility rather than buying water wholesale from a neighboring city the way some small Polk County towns do.</p>"),
            ("Fencing a run on a narrow in-town lot versus a new one",
             "<p>A fenced dog run behind one of the narrow lots near Dundee's own Main Street has less room to work with than a yard in Woodland Ranch Estates, where the builder's site plan already sets aside a fenced backyard on a wider pad. On the older lot, the run typically hugs one side yard and has to route around an existing oak's drip line; on the new one, the constraint is usually the builder's shallow topsoil over compacted fill rather than a lack of space. Either way, the base underneath doesn't change: the same two to four inches of washed rock, just measured against a different set of obstacles.</p>"),
        ],
        "scenario": ("Say you have a 15×20 dog run behind a Woodland Ranch Estates house",
                     f"<p>Say a new Woodland Ranch Estates house backs up to open space with a 15-by-20 dog run fenced off along one side, 300 sq ft in all. At {price('pet')} a square foot, that run prices between $3,000 and $5,400 installed, with the low end more likely on a pad that's already graded flat and the high end more likely if the crew has to break up compacted fill first to reach a real base. A run half that size behind an older Main Street lot scales the same way per square foot; what changes there is working around a fence line and a mature tree instead of a builder's site plan.</p>"),
        "faqs": [
            faq("Does Dundee's own water utility change how a dog run's irrigation gets capped?", "No. Florida's turf rule bars in-ground irrigation on synthetic turf regardless of whether the water comes from Dundee's public utility or a private well on an outlying lot, so the capping step at the valve box is identical either way."),
            faq("Is a weed barrier ever worth adding under Dundee pet turf given how fast Candler sand drains?", "Generally no. Fast native drainage helps the base shed liquid, but a fabric layer between the rock and the turf backing still traps urine at the surface instead of letting it filter through, which is why pet runs skip it even on Dundee's driest ridge lots."),
        ],
        "sources": SRC,
    },
    "putting": {
        "title": "Backyard Putting Greens in Dundee, FL – Ridge Slope",
        "meta": f"Backyard putting greens in Dundee, FL: natural ridge slope, Candler sand drainage and the {price('putting')} market range, checked September 2026.",
        "h1": "Putting Greens Built Into Dundee's Natural Ridge Grade",
        "lede": capsule(f"A backyard putting green in Dundee falls in the {price('putting')} per square foot band installers publish across Central Florida, and the ridge grade under many Dundee lots means a crew starts with real slope already in the ground instead of building every break by hand. The same Candler sand that drains the rest of a yard fast is why a green's own gravel base behaves predictably here."),
        "sections": [
            ("What a ridge lot's slope does for contouring",
             f"<p>Most putting-green subbases start flat and get shaped up from nothing, but a Dundee backyard on the ridge often already carries two or three feet of natural fall across its width, left over from the same dune-and-swale terrain that put eight lakes inside town limits and that keeps running south toward {city('lake-wales', 'Lake Wales')}. A crew still builds the green's own engineered base, angular aggregate compacted to a consistent depth, rather than shaping the native sand directly, because a green needs a subbase that won't shift under a rolled ball the way looser fill would. What the existing grade buys is fewer hours spent hauling in fill to create a break that wasn't there to begin with, and {post('artificial-turf-on-a-slope', 'our general guide to turf on a slope')} covers the anchoring details that apply whether the grade belongs to a green or a full lawn.</p>"),
            ("Sizing a green for an older Dundee lot near the depot",
             f"<p>A lot near Dundee's Main Street and the old depot rarely has room for more than a two- or three-cup green with a small chipping fringe, since these lots were platted before anyone was thinking about a short-game practice area in the backyard. A newer lot in a subdivision like Woodland Ranch Estates, with more square footage to work with, can support a longer green with more break built into it, or a shorter green paired with a fringe wide enough for real chipping practice. Both sizes use the same {svc('putting', 'synthetic putting surface')} and infill underneath; only the layout changes with the lot.</p>"),
            ("Keeping a green's edge off the state's waterbody setback",
             "<p>A handful of Dundee lots back onto Lake Menzie or Lake Annie closely enough that a full-yard putting green layout would otherwise want to run right up to the water. The state's rule treats a green the same as any other synthetic turf: it has to clear 10 feet of ordinary shoreline, a distance that only shrinks where a seawall already stands in for it, and it can't sit inside a swale or a pond's littoral zone at all. On most lots that still leaves enough room for a green with a real fringe and two or three cups, since a putting green rarely needs the full width of the yard the way a lawn conversion does.</p>"),
        ],
        "scenario": ("Say you have a 500 sq ft green on a Lake Annie lot",
                     f"<p>Say a Lake Annie lot has enough side yard, once the required setback is staked off, for a 500 sq ft green with a three-cup layout and a modest fringe. At {price('putting')} a square foot, that green prices between $7,000 and $15,000 installed, with contouring, cup count and fringe width doing most of the work of moving a specific quote up or down that range. A similarly sized green on a flatter in-town lot near the depot costs about the same; the difference shows up in how much fill the crew brings in to create the breaks the ridge lot already had.</p>"),
        "faqs": [
            faq("Does Dundee's ridge terrain make a putting green cheaper to build?", f"Not necessarily cheaper, but it can mean less imported fill to create interesting breaks, since several Dundee lots already carry real grade change. The published {price('putting')} per square foot range still depends more on cup count, fringe width and contouring than on how much natural slope a lot starts with."),
            faq("Do Dundee's lake lots limit where a putting green's cups can go?", "Only within the buffer strip itself. Cups and fringe both have to stay 10 feet off Lake Menzie, Marie or Annie's shoreline, a seawall being the sole exception, but a typical lakefront lot still has enough room outside that strip for a full green layout."),
        ],
        "sources": SRC,
    },
    "playground": {
        "title": "Playground Turf in Dundee, FL – Shade and Shock Pad",
        "meta": f"Playground turf in Dundee, FL: shock-pad fall-height sizing, oak-canopy shade near the depot and the {price('playground')} market range, September 2026.",
        "h1": "Playground Turf for Dundee Backyards, Shaded and New",
        "lede": capsule(f"Playground turf for a Dundee backyard runs {price('playground')} a square foot, the same range whether the swing set sits under old oak canopy near Main Street or on the open, sun-exposed pad of a new Woodland Ranch Estates lot. Fall height and shock-pad thickness, not the address, decide most of that price, and Dundee's own Development Services Department, not Polk County, reviews the permit either way."),
        "sections": [
            ("Shock-pad thickness against actual fall height",
             "<p>A play structure's fall height, the distance from the highest platform a child could fall from to the ground, is what actually sets shock-pad thickness under playground turf, not the size of the yard around it. Woodland Ranch Estates' own site plan includes a tot lot as one of its amenities, built to a commercial fall-height standard for shared equipment; a backyard swing set is almost always shorter than that, which means a residential pad usually runs thinner than what a shared subdivision amenity needs. Getting the fall height measured before ordering pad material is the step that keeps a home installation from over- or under-building the cushion underneath.</p>"),
            ("Oak shade near the depot changes the drip-line math",
             f"<p>The older lots ringing Dundee's Main Street and depot district often carry a live oak old enough to shade half a backyard, which is good news for a play structure baking in Florida sun but a real constraint on where turf can go. The state's rule keeps synthetic turf out of a tree's drip line on the property it's on, or an adjacent one, unless a certified arborist signs off, and a play area is exactly the kind of feature families want tucked under that same shade. Mapping the canopy's actual reach before laying out the turf, not just eyeballing the trunk, is what keeps a shaded play area from crossing that line, and {post('artificial-turf-near-live-oaks-and-palms', 'our guide to turf near live oaks')} goes deeper into how root systems and drip lines interact with an install.</p>"),
            ("Full sun on a new Woodland Ranch Estates lot",
             "<p>A new lot in Woodland Ranch Estates has none of the depot district's oak cover yet, since the subdivision's trees are still young landscaping rather than a decades-old canopy, which means a play area there sits in full Florida sun most of the day. Surface temperatures on unshaded synthetic turf commonly run 120 to 150°F and can pass 160°F, so a quick hose rinse before playtime and a lighter-colored infill both matter more here than under an old oak. Planning for shade later, a young tree planted near enough to eventually screen the play area, is worth doing at installation rather than after the fact.</p>"),
        ],
        "scenario": ("Say you have a 250 sq ft play area behind a new Dundee house",
                     f"<p>Say a young family on a new Woodland Ranch Estates lot wants a 250 sq ft play area under a swing set with a six-foot fall height. At {price('playground')} a square foot, that area prices between $2,500 and $6,250 installed, with the shock pad's thickness, sized to that six-foot fall height, doing most of the work of landing near the top or bottom of the range. A similar play area tucked under an old oak near Main Street prices the same per square foot, minus whatever the drip-line rule trims off the usable footprint first.</p>"),
        "faqs": [
            faq("Does a Woodland Ranch Estates tot lot use the same turf as a backyard play area?", "The subdivision's own shared tot lot is built to a commercial fall-height standard for equipment used by many children, so its shock pad usually runs thicker than what a single home's swing set needs. The underlying materials, permeable-backed turf over a rock base, are the same idea at a different scale."),
            faq("Do Dundee's older oak-shaded lots need a thinner shock pad than a sunny new one?", "Shade changes comfort and surface heat, not the pad thickness a shock rating requires. Fall height from the specific equipment still sets shock-pad depth, whether the play area sits under a mature oak near the depot or in the open sun of a new subdivision lot."),
        ],
        "sources": SRC,
    },
    "pool": {
        "title": "Pool & Lanai Turf in Dundee, FL – Full-Sun Ridge",
        "meta": f"Turf around a Dundee pool cage or lanai: drainage underlay over concrete, ridge-sun heat and the {price('residential')} market range, September 2026.",
        "h1": "Turf for Dundee Pool Cages and Screened Lanais",
        "lede": capsule(f"Turf beside a screened Dundee pool prices the same as any residential lawn, {price('residential')} a square foot, and it's the ridge's open, full-sun exposure, more than the pool water itself, that decides how that turf has to be built. A strip inside a lanai over existing concrete needs a drainage layer the surrounding yard doesn't, whether the house sits downtown or on a new Woodland Ranch Estates lot."),
        "sections": [
            ("Why a lanai deck needs its own drainage layer",
             "<p>Turf laid inside a screened pool cage almost always sits on an existing concrete deck rather than bare soil, and concrete doesn't drain the way a washed-rock base does, so a drainage underlay goes between the slab and the turf backing to give rinse water and rain somewhere to go besides sitting on top of the concrete. The perimeter gets glued rather than staked, since there's no soil at the deck's edge for a nail to grip, and that glued bond is usually the first thing to check after a season of pool splash-out and hose rinsing. None of this changes with a house's location in Dundee; a lanai on a ridge lot and one two blocks from Lake Marie get the same deck treatment.</p>"),
            ("Full sun on an open ridge lot versus a shaded in-town yard",
             f"<p>Away from Dundee's older, tree-lined blocks, a lot on open ridge ground can leave a pool deck and its surrounding turf in full sun most of the day, the same exposure a crew sees on similar ridge lots toward {city('lake-alfred', 'Lake Alfred')} and {city('davenport', 'Davenport')}, which pushes surface temperatures well past what the same turf would reach under an oak canopy near the depot. A hose rinse drops that temperature 30 to 50 degrees within minutes, which matters more around a pool deck than almost anywhere else in the yard, since bare feet cross it constantly between the water and a lounge chair. A lighter-colored infill or a planned shade sail over part of the deck both help on a lot that doesn't have mature trees to lean on yet.</p>"),
            ("Keeping capped irrigation clear of a pool equipment pad",
             "<p>A pool equipment pad usually sits close to whatever irrigation zone used to water that side of the house, and capping those heads at the valve box, required once turf goes down, needs to happen without blocking access to the pump and filter housing later. On an older Dundee lot that equipment pad is often original to the pool's installation decades ago; on a new Woodland Ranch Estates build, it's recent enough that the irrigation plan and the pool equipment layout were at least drawn on the same site plan. Either way, marking the pad's service clearance before finalizing where turf and its edging go avoids a callback to move something that should have stayed put.</p>"),
        ],
        "scenario": ("Say you have a 300 sq ft strip around a Dundee pool cage",
                     f"<p>Say a resurfaced pool on an older Dundee lot has a 300 sq ft ring of bare dirt and dead grass between the deck and the screen enclosure's frame. At {price('residential')} a square foot, that strip prices between $2,400 and $5,400 installed, with the deck's own drainage underlay pushing toward the higher end and a simple soil-based strip along the outside of the cage pushing toward the lower one. The same strip on a new Woodland Ranch Estates pool home prices identically per square foot, since the deck's construction, not the neighborhood, sets where in that range a specific job lands.</p>"),
        "faqs": [
            faq("Does turf around a Dundee pool need a different infill because of chlorine splash-out?", "No infill change is needed for chlorine specifically. Silica sand or coated sand both hold up fine against occasional splash-out; the bigger consideration around a pool deck is the drainage underlay under the turf, not the infill on top of it."),
            faq("Is a shaded in-town pool lanai cooler than one on an open ridge lot?", "Usually, yes, if mature trees actually block direct sun for part of the day. Surface temperature is the main difference; the turf construction, drainage layer and glued edges over the concrete deck, stays the same regardless of how much shade a specific Dundee lot gets."),
        ],
        "sources": SRC,
    },
    "repair": {
        "title": "Artificial Turf Repair in Dundee, FL – Ridge Lot Fixes",
        "meta": "Turf repair in Dundee, FL: lifted seams, storm-anchoring checks and Candler-sand base fixes, quoted after photos or a site visit, September 2026.",
        "h1": "Fixing Dundee Turf: Seams, Edges and Rushed Bases",
        "lede": capsule("A lifted seam or a scorched patch on a Dundee lawn gets priced after photos or a short visit, not a number quoted over the phone, since what actually failed underneath, a shifting Candler-sand base, a rushed edge, a low-E window reflection, changes the fix more than the square footage does. Dundee's own Development Services Department, not Polk County, still reviews any permit a larger repair might trigger."),
        "sections": [
            ("Why a ridge lot's base fails differently than a flatwoods one",
             "<p>A rushed base on a Dundee ridge lot doesn't usually fail the way one does on the flatwoods soil around Kissimmee, where a high water table is the main enemy. Here the problem is more often loose Candler sand working its way up through a base that wasn't compacted in proper lifts, or an edge that was stapled into sand that never held the fastener the way heavier soil would. Both show up the same way eventually, a corner that lifts, a section that feels soft underfoot, but the fix on a ridge lot usually means re-anchoring into a deeper, better-compacted base rather than correcting a drainage problem.</p>"),
            ("Storm-season checks after a ridge lot's afternoon downpour",
             f"<p>Central Florida's summer storms can drop an inch or more of rain in under an hour, and on an exposed ridge lot without much windbreak, the same storm brings wind gusts that test every staple and glued seam a lawn has. Walking the perimeter after a hard storm, checking specifically for a lifted corner or a seam that's started to peel, catches most repair needs while they're still small enough to re-anchor rather than replace. A lawn that's cleared two or three rainy seasons without a lifted edge has usually proven its anchoring was done right the first time, a pattern {post('does-artificial-turf-drain-in-heavy-rain', 'covered in more depth here')}.</p>"),
            ("Matching an older Main Street driveway edge",
             "<p>Where an older lot near Main Street backs turf up to a driveway or walkway poured decades ago, that edge is often the first place a repair call comes from, since the original slab has settled unevenly in a way a newer Woodland Ranch Estates driveway hasn't yet had time to do. A glued edge that was never feathered to match the slab's actual height, rather than a flat, freshly poured one, tends to show a gap or a ridge sooner than the rest of the perimeter. Re-trimming and re-gluing that one transition is usually a smaller job than the lifted edge first suggests, once photos show exactly where the slab has moved.</p>"),
        ],
        "scenario": ("Say you have a lifted 8-ft seam along one side of the yard",
                     "<p>Say a five-year-old Dundee lawn has an 8-ft seam lifting along one edge after a summer of hard afternoon storms, with the turf on either side still holding flat. Whether that's a quick re-glue or a sign the base underneath has washed out along that whole edge isn't something to guess at over the phone, since one fix takes an hour and the other means pulling back several feet of turf to rebuild the rock underneath. A few photos of the lifted section, plus its approximate length, are usually enough for a first read; a short site visit confirms it before any number gets quoted.</p>"),
        "faqs": [
            faq("Does a Dundee repair need the town's permit if it's just fixing a seam?", "Almost never. A seam or edge repair on existing turf typically doesn't rise to the level of Dundee's building permit process, though a repair that involves regrading a larger section or moving drainage is worth a quick call to Development Services to check before starting."),
            faq("Why would a five-year-old Dundee lawn need a different fix than a brand-new one?", "Age changes what's actually wrong more than it changes the diagnosis process. An older lawn's problem is more often infill loss or a base that's finally shown a compaction gap; a newer lawn's issue is more often a single bad seam or edge from the original install, not a wear problem."),
            faq("What should the best artificial turf repair company near me in Dundee ask before quoting a fix?", "Whether they ask for photos and the approximate size of the damaged area before naming a number, and whether they ask what's underneath, ridge sand or an older base, rather than assuming every repair is a simple re-glue. A company that quotes a firm price sight unseen is skipping the step that actually determines the fix."),
        ],
        "sources": SRC,
    },
}


def get_pages():
    return [HUB] + cityservice_pages(SLUG, LOCAL)
