# -*- coding: utf-8 -*-
"""Service pages: pool & lanai turf, vacation rental turf, commercial turf, sports & fitness turf."""
from _helpers import page, capsule, sec, table, faq, ul, steps, note, cta, a, svc, city, county, post, src, ext, price, price_note, tel


def _pool():
    body = "".join([
        sec("Who this fits, and who should look elsewhere",
            "<p>Artificial turf around a pool solves one specific problem: the strip of ground between the deck and the fence that never gets full sun once a screen enclosure goes up, or the slab inside the cage where nothing was ever meant to grow. It suits pool homes in Kissimmee, St. Cloud and Hunters Creek where St. Augustine has thinned out behind the cage, lanais where the floor is bare concrete, and rental homes that need the yard to look finished in every listing photo without a mowing crew scheduled around guests.</p>"
            + f"<p>It doesn't fit every pool yard. If the area between the deck and a retention pond is already a planted buffer, turf isn't the answer there, because the state's synthetic turf standard keeps it 10 feet back from a lake, pond or canal unless a seawall or bulkhead already lines the bank (a swimming pool itself doesn't trigger that setback; an open pond behind the pool cage does). And if you're picturing turf that feels cool underfoot at two in the afternoon in July, that's not how any dark synthetic surface in full sun behaves, ours included. More on that below, honestly, not glossed over.</p>"),
        sec("Pool turf options: deck border, lanai floor, and paver joints",
            "<p>\"Pool turf\" covers a few different builds depending on what's under it. A border between the deck and the fence line gets a base of washed, open-graded crushed rock, compacted firm without packing the native sand underneath so tight that it quits draining, the same as any side yard build. A screen enclosure or lanai floor is almost always bare concrete, so the turf gets glued down instead of seamed over soil. A narrow accent strip between pavers at the pool is a different job again: a ribbon of turf cut to width and set into the joint rather than a walking surface.</p>"
            + table("Pool-area turf builds in Kissimmee", ["Area", "Typical build", "Suited to"],
                    [["Open deck border", "Washed crushed-rock base (2–4 in.), seamed turf, bender-board or paver edge", "Sunny strips between the pool deck and a side fence"],
                     ["Screen enclosure or lanai floor", "Glue-down over the existing concrete slab with a drainage underlay", "Cages where soil was never brought in to begin with"],
                     ["Between pavers at the pool", "Turf ribbon cut to width, glued into the paver joint", "Accent lines and stepping paths, not full traffic zones"],
                     ["Splash zone near the water", f"Standard {a('/compare/nylon-vs-polyethylene-vs-polypropylene-turf/', 'polyethylene turf')}, rinsed the same as any deck runoff", "Areas that take regular chlorine or saltwater overspray"]],
                    "Chlorine and saltwater in normal splash amounts don't discolor or break down the fibers; concentrated pool chemicals spilled straight onto turf can, so store shock and acid away from the edge and hose off any spill.")),
        sec("Can turf go inside a screen enclosure or next to a saltwater pool?",
            f"<p>Yes to both. Inside a screen enclosure, turf is glued directly to the existing concrete slab over a thin drainage underlay, since there's no soil there to build a normal base from. Saltwater and chlorine splash don't damage the polyethylene fibers used in landscape turf; fiber makers test against pool chemistry and salt exposure and report no fading or breakdown from ordinary contact ({ext('https://turfgrass.net/inspiration/how-chlorine-affects-artificial-grass', 'chlorine-resistance testing summary')}). Standing puddles of pool water on the turf just need a rinse, same as a wet deck.</p>"
            + "<p>The detail that trips up a DIY glue-down is drainage. A pool cage floor has nowhere for water to go except an existing deck drain, so the underlay has to route splash and rinse water to that drain rather than letting it pool underneath the turf and turn sour. Seams inside a cage run parallel to the screen frame, not across the path people walk, so foot traffic doesn't work them open over time.</p>"),
        sec("How we build turf on a pool deck or lanai floor",
            steps([("Check the existing slope.", "Pool decks and lanai floors are already pitched to a drain. We confirm it still runs the right direction before anything new goes down."),
                   ("Clean and prep the slab.", "The concrete gets pressure washed, and any curling paint, sealer or old adhesive residue comes off so the new glue bonds to bare concrete."),
                   ("Lay the drainage underlay.", "A thin perforated mat goes down first so splash, rinse and any wind-blown rain reach the deck drain instead of collecting under the turf."),
                   ("Glue rather than nail.", "Turf on concrete is bonded with polyurethane adhesive along every edge and seam; there's no way to drive a perimeter nail into a slab."),
                   ("Seam away from the walking path.", "Seams are placed parallel to the cage frame so the heaviest foot traffic, not the glue line, takes the wear."),
                   ("Cut around posts and drains.", "Screen posts, drain covers and skimmer lids get trimmed around and left fully accessible for service."),
                   ("Light infill, brush, first rinse.", "A light infill and an initial hose-down settle the blades before we walk every seam one more time.")])),
        sec("What artificial turf around a pool costs in Kissimmee",
            f"<p>Pool-area turf prices from the same {price('residential')} per square foot range as any residential job, with most yards landing between {price('residential', True)}. Glue-down work over an existing slab usually prices toward the top of that range rather than the middle, because there's no excavation to offset the adhesive labor and drainage underlay. Say a 500 sq ft lanai gets glued to the existing floor: at $16 to $18 a square foot for that kind of work, the job runs roughly $8,000 to $9,000, higher than the same square footage would cost as an open backyard border.</p>"
            + f"<p>Open deck borders and turf between pavers price closer to the middle of the range, since they're built the normal way, over a compacted washed-rock base rather than glued to concrete. The {a('/artificial-turf-cost/', 'full cost guide')} breaks the range down further by yard size, and {post('install-artificial-turf-over-concrete-pavers-or-grass', 'this piece on installing over concrete, pavers or grass')} goes into the labor difference in more depth.</p>"),
        sec("Heat, storms and window glare next to the pool",
            f"<p>Be honest about heat before you commit a whole pool deck border to turf. In full Florida summer sun, synthetic turf commonly reaches 120 to 150°F at the surface and can go higher; a 30-second hose rinse drops that 30 to 50 degrees within minutes ({src('magnolia-heat', 'Florida installer measurements')}). A pool deck already gets hot underfoot in July, concrete included, but bare feet moving from tile to turf will notice the difference at midday. Shade sails, a lighter infill color and a rinse before pool time help; an unshaded, west-facing strip is a place we'll say so upfront.</p>"
            + f"<p>Perforated turf backing drains faster than 30 inches of water an hour ({src('sgw-faq', 'manufacturer FAQ on drainage rate')}), well beyond what a Central Florida summer storm delivers, but a glue-down lanai floor is only as good as the deck drain it feeds. If that drain is already slow, turf won't fix it. Window and door glass near a pool cage, especially large west- or south-facing sliders in newer pool homes, can reflect enough concentrated sunlight to soften synthetic turf; {post('can-artificial-turf-melt', 'turf can melt from that kind of reflected glare')}, so we check nearby glass before quoting. Sprinkler heads that used to water the strip behind the cage get capped once turf goes down; the state's 2026 turf rule doesn't allow an in-ground system to irrigate synthetic turf.</p>"),
        sec("HOA rules and Florida law for turf around a pool",
            f"<p>{a('/laws/florida-hb-683/', 'Florida’s HB 683')} and the adopted DEP rule that carries it out, {src('dep-rule', 'Rule 62-308.100')}, apply to turf on a single-family lot of an acre or less, and a pool deck or lanai on that kind of lot is covered. The standard requires permeable turf free of intentionally added PFAS and heavy metals, keeps turf out of a tree's drip line without an arborist's sign-off, and keeps it at least 10 feet from the ordinary water line of a lake, pond or canal unless the bank already has a seawall or bulkhead. A swimming pool itself isn't a waterbody under that rule; a retention pond behind the pool cage is. Most pool cages sit well inside a fenced backyard, which is also the part of the lot {a('/laws/hoa-rules/', 'Florida law protects from HOA restriction')} when it isn't visible from the street or a neighboring parcel.</p>"
            + f"<p>None of that is legal advice, and the rule itself creates no new DEP permit; what still varies by city and county is the permit for the underlying screen enclosure or deck work. {a('/laws/permits/', 'The permit guide')} lists what each Osceola, Orange, Polk, Lake and Seminole office asks for.</p>"),
        sec("What goes wrong with a bad pool-turf install",
            ul(["<strong>Nailed edges on concrete.</strong> A perimeter can't be nailed into a slab; if it was, expect the edge to lift within a season.",
                "<strong>No drainage underlay.</strong> Water sits under the turf inside the cage, and the space starts to smell like standing pool runoff.",
                "<strong>Seams cut across the traffic path.</strong> The heaviest foot traffic on a lanai runs straight through the middle, and a seam placed there opens faster than one placed to the side.",
                "<strong>Screen posts and drain lids ignored.</strong> Turf trimmed loosely around a post or drain leaves a gap that collects debris and gives ants a way in.",
                "<strong>Wrong infill choice.</strong> A basic silica infill holds chlorine residue and salt spray longer than a coated or antimicrobial infill does in a splash zone, and the state standard limits a house lot to natural infill anyway: clean silica, zeolite or a non-toxic coated sand, not a rubber or synthetic product."]),
            "pool-issues"),
        sec("Caring for turf around a pool",
            f"<p>Rinse chemical splash and leaf litter off with a hose rather than letting it dry into the fibers, and keep shock, acid and other concentrated pool chemicals stored away from the turf's edge. Brush the path from the lounge chairs to the pool steps a few times a year so the blades don't mat flat where everyone walks. After a named storm, walk the glued edges and any seam near the screen frame; the state standard requires edges and seams to be anchored against wind and flooding, and a lifted corner caught early is a small {svc('repair', 'repair')} rather than a redo. {svc('cleaning', 'A yearly power-broom and infill top-up')} keeps a pool-deck lawn looking the way it did on day one.</p>"),
        sec("How do you find the best pool turf installer near you in Kissimmee?",
            "<p>Ask specifically about the parts of a pool job that a regular lawn install doesn't cover. Does the quote say the lanai floor gets glued, or does it just say \"installed\"? Is there a named drainage underlay, or is that assumed? How does the crew plan to route water to the existing deck drain, and what happens to the screen posts and skimmer lids during the cut? A written answer to those four questions tells you more than any claim about who's the top choice in town, and it lets you compare two bids on the same terms.</p>"),
        sec("Where we do this work near Kissimmee",
            f"<p>Pool-home turf is common work from {city('kissimmee')} and {city('st-cloud')} through {city('hunters-creek')}, {city('celebration')} and the resort belt at {city('four-corners')}, {city('championsgate')} and {city('reunion')}, where a screen-caged pool sits behind most houses.</p>"
            + "<!--AUTO:service-cities-->"),
    ])
    faqs = [
        faq("Will pool chemicals ruin artificial turf if I spill some?", "Diluted splash and everyday chlorine or salt exposure don't damage landscape turf, but a concentrated spill of shock, acid or algaecide can discolor or stiffen the fibers where it lands. Keep chemical containers off the turf and rinse any spill right away."),
        faq("Can turf run right up to the pool coping?", "Yes, if there's a firm edge to glue or nail into. Against loose gravel or a soft coping edge, we add a paver or metal edge strip first so the turf has something solid to anchor to."),
        faq("Does turf make a wet pool deck more slippery?", "Not more than wet tile or wet concrete. The backing is permeable, so water passes through rather than sitting on the surface, but any wet surface near a pool still calls for the usual care around the steps."),
        faq("Can turf go over pavers inside a lanai instead of bare concrete?", "Yes. Well-set pavers take turf almost the same way a slab does, usually with a thin leveling layer first. Loose or shifting pavers need to be reset before turf goes down, or the turf will telegraph the movement."),
        faq("Do you cap the sprinkler heads near the pool deck?", "Yes, any head that used to water the strip behind the cage gets capped at the line once turf replaces that area. The 2026 state turf standard doesn't allow an in-ground system to irrigate synthetic turf."),
        faq("How hot does pool-deck turf get compared to the pavers around it?", "Both get hot in full sun; turf can reach 120 to 150°F, similar to dark pavers or stamped concrete in the same exposure. A rinse cools either surface quickly, which is why a hose bib near the pool matters more than the surface choice."),
        faq("Is turf a problem for a pool near a retention pond?", "Only near the pond, not near the pool. The state's setback keeps synthetic turf at least 10 feet from the water line of a pond, lake or canal unless a seawall or bulkhead is already built along it, so we hold the turf back from an open bank and treat the pool-side area normally."),
    ]
    return page("/pool-turf/", "service",
                "Artificial Turf Around a Pool in Kissimmee, FL",
                "Artificial turf around a pool in Kissimmee, FL: glue-down lanai floors, drainage underlay, chlorine and saltwater facts, heat honesty and 2026 prices.",
                "Getting Artificial Turf Around a Pool Right in Kissimmee",
                capsule("Artificial turf around a pool in Kissimmee replaces the strip of St. Augustine that quits once a screen enclosure blocks the sun. Installed turf runs $8 to $18 a square foot as of September 2026, glued to the pool deck or lanai floor over a drainage underlay, or seamed over a graded base beside it, usually in two to four days."),
                body, faqs=faqs, service="pool", crumbs=[("Services", "/services/")], crumb="Pool & lanai turf",
                sources=["hb683", "dep-rule", "marathon-pr", "fs7203045", "magnolia-heat", "sgw-faq", "attampa-cost", "lbs-fl-cost",
                         ("Turfgrass.net — how chlorine affects artificial grass", "https://turfgrass.net/inspiration/how-chlorine-affects-artificial-grass")],
                related=[("/turf-and-pavers/", "Turf between pavers and stepping paths"), ("/vacation-rental-turf/", "Turf for vacation rental pool homes"),
                         ("/blog/can-artificial-turf-melt/", "Can artificial turf melt?"), ("/blog/install-artificial-turf-over-concrete-pavers-or-grass/", "Installing turf over concrete, pavers or grass"),
                         ("/artificial-turf-cost/", "Full turf cost guide with tables"), ("/laws/hoa-rules/", "What a Florida HOA can restrict")])


def _str():
    body = "".join([
        sec("Why short-term rental yards near Disney need a different plan",
            f"<p>A vacation rental yard around {city('kissimmee')} does a different job than a family lawn. Nobody lives there to notice a thin patch before it spreads, guests walk the same path from the driveway to the pool cage every single week, and the owner is often hours away or managing the property through someone else entirely. Sod that would recover fine under one family's normal wear struggles under a rotating set of strangers, suitcases and the occasional cooler dragged across the grass.</p>"
            + f"<p>Artificial turf for vacation rental homes fits the pool-home belt especially well: {city('four-corners')}, {city('championsgate')}, {city('reunion')}, {city('davenport')} and {city('celebration')}, where a large share of houses run as short-term rentals rather than owner-occupied homes. It's a weaker fit for a rental that's rarely booked and sits mostly empty, where the wear that turf is built for never really happens, or for an owner who enjoys the yard work themselves between longer-term tenants.</p>"),
        sec("What it is, what it costs, and how long it takes",
            f"<p>The build itself isn't different from any residential lawn: sod and a few inches of soil come out, then two to four inches of washed, open-graded crushed rock get compacted firm on top of native sand left loose enough to keep percolating, and turf gets seamed, edged and infilled on top. What changes is the scheduling and the spec. Installed turf runs {price('residential')} per square foot as of September 2026, with most yards between {price('residential', True)}, and a typical rental-home yard of 600 to 1,000 sq ft takes two to four days once the base is graded. Property managers usually want that window to land inside a gap between bookings rather than during a stay.</p>"),
        sec("Turf options for a rental yard: pool cage, open backyard, pet-friendly upgrade",
            table("Turf builds for short-term rental homes", ["Area", "Typical build", "Why it matters for a rental"],
                  [["Pool cage or lanai edge", "Compacted base or glue-down over the slab, same as any pool-home yard", "Usually the first thing guests photograph and the first thing they walk on"],
                   ["Open backyard", "Standard residential build, curves smoothed for easy mowing-free upkeep", "Fills the listing photo without a lawn crew visible in it"],
                   ["Side yard or dog run", f"{a('/pet-turf/', 'Pet-turf build')} with permeable backing and odor-control infill", "Many listings now advertise as pet-friendly, and guest dogs use the yard hard"],
                   ["Front strip visible from the street", "Standard build, subject to any HOA architectural review", "Not protected the way a fenced backyard is under Florida's HOA statute"]],
                  "Builds are the same materials as any residential job; what differs is which parts of the yard get prioritized for a rental's traffic pattern.")),
        sec("Is artificial turf a good investment for an Airbnb or vacation home near Disney?",
            "<p>It can be, for the right property, but the answer depends on what you're currently paying for lawn care and irrigation, not on a number we can promise. Turf removes the recurring mowing bill and the guesswork of scheduling a lawn crew around check-ins, and it holds up to guest traffic better than a lawn nobody's watching day to day. It doesn't pay for itself on day one. Run the arithmetic on your own lawn and water bill before deciding, using the worked example below.</p>"
            + table("Worked example: turf payback against a lawn-service bill (900 sq ft, hypothetical numbers)",
                    ["Line", "Amount"],
                    [["Lawn service and irrigation you're currently paying", "$120 a month (plug in your own)"],
                     ["Annual cost of that service", "$120 × 12 = $1,440 a year"],
                     ["Installed turf for 900 sq ft at the typical range", "$9,000–$14,400"],
                     ["Years to offset the install cost from that bill alone", "About 6 to 10 years"]],
                    "This is arithmetic on a hypothetical bill, not a projection for your property. Lower your own lawn bill into the formula and the payback period moves accordingly; if you already mow it yourself, the math looks very different.")
            + f"<p>{post('does-artificial-grass-increase-home-value-florida', 'Whether turf adds resale value')} is a separate question from whether it pays back on upkeep, and the two shouldn't be mixed together in a pitch. What we can say plainly: turf removes irrigation scheduling entirely, which matters on Toho Water's two-day-a-week watering limit, and it removes the risk of a lawn crew showing up loud with a mower during a guest's stay.</p>"),
        sec("How we build a rental-home yard for guest traffic",
            steps([("We coordinate through whoever manages access.", "Owner, property manager or cleaning company, we work with whoever holds the gate code and the booking calendar."),
                   ("We schedule inside a vacancy.", "Most residential yards take two to four days; we aim to start and finish inside a single gap between checkout and the next check-in when the calendar allows it."),
                   ("Edges get fastened for heavier traffic.", "Perimeter nails go in on a tighter spacing than a family-yard job, since suitcases, coolers and extra feet put more stress on an edge."),
                   ("Adhesive cures before anyone walks it.", "Glued seams and edges get time to set before the property goes back on the booking calendar, so no one arrives to wet adhesive."),
                   ("We flag the irrigation zone.", "Heads that watered the old lawn get capped, and we tell the property manager which zone is now dry so a lawn contractor doesn't keep running it."),
                   ("Walkthrough goes to whoever will actually see it.", "We go over rinsing and brushing with the cleaning crew or manager, not just the owner, since they're the ones on site between guests.")])),
        sec("Guest wear, lawn-service coordination and Florida storms",
            f"<p>Guests are harder on a yard than a homeowner in some ways and easier in others. They don't dig up a corner to plant tomatoes, but they do drag furniture, run a cooler across the same six feet of turf all week, and let kids play barefoot in July heat without thinking about it. Surface temperatures on synthetic turf commonly run 120 to 150°F in full sun ({src('horsemans-heat', 'measured Florida summer readings')}); a note in the house manual about a quick hose rinse before pool time solves most of that, and it's worth adding to the guest guide once turf goes in.</p>"
            + f"<p>Afternoon storms drain through perforated turf faster than 30 inches an hour, well beyond what a Central Florida downpour delivers, so a well-graded rental yard won't hold water the way tired sod under a rain gutter sometimes does. Large west-facing great-room windows are common in newer resort-community homes; check that glass before finishing a job near it, since reflected glare can soften turf the same way it can near a pool ({post('can-artificial-turf-melt', 'more on that here')}). Once turf is in, cancel or redirect the irrigation zone that used to run it; the 2026 state standard doesn't allow an in-ground system to water synthetic turf, and a lawn contractor still running that zone on a timer is money down a capped pipe.</p>"),
        sec("HOA and resort-community approval for rental-home turf",
            f"<p>A large share of the short-term rental belt around {city('four-corners')} and {city('championsgate')} sits inside HOA or resort communities with an architectural review process, and each community sets its own rules, so check the specific one before assuming anything. What Florida law sets statewide: {a('/laws/florida-hb-683/', 'HB 683')} and {src('dep-rule', 'the adopted DEP rule')} behind it stop a city or county from banning turf that meets the state standard on a single-family lot of an acre or less, but that law says nothing about a private HOA. A rental home is a single-family lot, so the same standard applies: infill has to be a natural material such as silica, zeolite or coated sand rather than rubber crumb, the rock base underneath has to be washed so it doesn't cake, and turf stays at least 10 feet from a lake, pond or canal's edge unless a seawall or bulkhead already runs along it, worth knowing on the many lakefront lots through this belt. Separately, {a('/laws/hoa-rules/', 'F.S. 720.3045')} keeps an association from restricting artificial turf in a fenced backyard that isn't visible from the street or a neighboring lot; a front yard doesn't get that protection and usually still needs an architectural submittal.</p>"
            + f"<p>We prepare that submittal, a sample, a spec sheet and a site plan, when a community wants one. {a('/laws/permits/', 'The permit guide')} covers what each county and city office asks for beyond the HOA layer.</p>"),
        sec("What goes wrong with a bad rental-yard turf install",
            ul(["<strong>Seams and edges not built for extra traffic.</strong> A standard nail spacing that's fine for a family yard can work loose faster under repeat guest wear.",
                "<strong>Nobody told the cleaning crew.</strong> A rinse or brushing routine only works if whoever's on site between bookings actually knows it.",
                "<strong>Wrong infill for a pet-friendly listing.</strong> A steady rotation of different guest dogs needs odor-control infill from day one, not after complaints start.",
                "<strong>Installed mid-season without checking the calendar.</strong> A job that runs long into a check-in date creates a bad first impression for the very guest paying to see a finished yard.",
                "<strong>Turf laid over the septic lid.</strong> On lots with a septic system, the state standard requires that access lid stay reachable for a pump-out, so seams and edging route around it instead of over it."])),
        sec("Caring for turf between bookings",
            f"<p>Whoever cleans the house between stays can handle most of it: blow leaves and debris off before the next guest, spot-rinse anything spilled near the pool cage, and brush the main walking path against the grain every few turnovers so it stands back up for photos. A quarterly deeper brush and infill check, done by us or by the property manager's regular vendor, keeps the yard from looking flat in new listing photos. {svc('cleaning', 'A yearly power-broom and refresh')} is worth budgeting the same way pool service already is.</p>"),
        sec("How do property managers find the best turf contractor near them?",
            "<p>The property managers who handle several rental homes tend to ask a different set of questions than a single homeowner would. Can the scope be written once and reused across a portfolio of similar homes? Is scheduling flexible enough to fit inside a booking gap rather than blocking out a week? Are repairs quoted per visit or does an installer expect a standing service arrangement? None of that is a claim about who ranks first in Kissimmee; it's simply what a working relationship with a rental-portfolio manager needs to include before either side signs anything.</p>"),
        sec("Where the short-term rental belt runs",
            f"<p>Most of our vacation-rental calls come from {city('four-corners')}, {city('championsgate')}, {city('reunion')}, {city('davenport')} and {city('kissimmee')} itself, with a smaller share from longer-term rentals in {city('celebration')} and {city('poinciana')}.</p>"
            + "<!--AUTO:service-cities-->"),
    ])
    faqs = [
        faq("Does artificial turf help or hurt vacation rental listing photos?", "It usually helps. A flat, evenly green yard photographs consistently in every listing, in every season, without depending on when the lawn crew last mowed. Brush the main walking path against the grain before a photo shoot so the blades stand up instead of lying flat from foot traffic."),
        faq("Will guests complain that the yard isn't real grass?", "Some notice, most don't mention it, and a few specifically like that there's no wet grass or fire ants to deal with barefoot. Listing the yard honestly as turf in the description heads off any surprise on arrival."),
        faq("Can you install turf while the property is actively booked?", "We schedule around the calendar whenever possible and prefer a gap between checkout and the next check-in. A rush job squeezed around active guests is possible but isn't the smoothest way to do it, and adhesive and infill need time to settle before anyone walks the yard."),
        faq("Does turf work for a pet-friendly rental with a rotating set of guest dogs?", f"Yes, if it's built like {svc('pet', 'pet turf')} from the start: fully permeable backing, no weed fabric underneath, and an odor-control infill sized for regular use by different dogs rather than one household's pet."),
        faq("Who do you coordinate with if the owner lives out of state?", "Whoever holds the gate code and the calendar, usually a property manager or the cleaning company. We're used to scheduling site visits and installs through a third party rather than the owner directly."),
        faq("Is turf worth it for a rental we only run part of the year?", "It still removes the mowing schedule and irrigation worry for the months it sits idle, which is often when an unattended lawn looks worst in photos. The payback math in the table above moves slower with fewer months of avoided lawn-service bills, so run your own numbers before committing."),
        faq("Can we turf only the areas guests photograph and leave the rest?", "Yes, and it's a common way to phase the budget. The pool cage and the section visible from the lanai doors are usually first, with a side yard or dog run added later if it makes sense."),
        faq("Do resort communities near Disney allow artificial turf?", "Rules vary by community and change over time, so check your specific HOA's current architectural guidelines rather than assuming. Statewide, Florida law protects a fenced backyard not visible from the street from an HOA turf ban; a front yard typically still needs review."),
    ]
    return page("/vacation-rental-turf/", "service",
                "Artificial Turf for Vacation Rental Homes in Kissimmee",
                "Artificial turf for vacation rental homes near Disney: guest-proof yards, HOA notes for Four Corners and ChampionsGate, and a payback worksheet.",
                "Artificial Turf for Vacation Rental Homes: What Property Managers Ask",
                capsule("Artificial turf for vacation rental homes near Kissimmee and Disney removes the mowing schedule and the guesswork of coordinating a lawn crew around guests. Installed turf runs $8 to $18 a square foot as of September 2026, most yards $10 to $16, and a typical 600 to 1,000 sq ft rental yard is built in two to four days, ideally inside a gap between bookings."),
                body, faqs=faqs, service="str", crumbs=[("Services", "/services/")], crumb="Vacation rentals",
                sources=["attampa-cost", "lbs-fl-cost", "toho-days", "hb683", "dep-rule", "fs7203045", "horsemans-heat", "bearcat-10yr"],
                related=[("/pet-turf/", "Pet turf for a pet-friendly listing"), ("/pool-turf/", "Turf around the pool and lanai"),
                         ("/blog/does-artificial-grass-increase-home-value-florida/", "Does turf increase home value in Florida?"),
                         ("/blog/what-to-expect-on-turf-installation-day/", "What to expect on installation day"),
                         ("/artificial-turf-cost/", "Full turf cost guide with tables"), ("/laws/hoa-rules/", "What a Florida HOA can restrict")])


def _commercial():
    body = "".join([
        sec("What counts as commercial turf around Kissimmee",
            "<p>Commercial artificial turf installation covers any job on a shared or managed property rather than a single house: an HOA's clubhouse lawn, an apartment complex's dog park, a restaurant patio, a daycare's play yard, a rooftop deck or a storefront's landscaping. The site is different from a house lot in ways that change the build: more people or dogs use it every day than any one household's turf sees, the surface it sits on might be a rooftop membrane or a parking structure instead of dirt, and whoever's paying is usually a board, a manager or a general contractor rather than the person walking on it.</p>"
            + "<p>It's not the right fit for a full-size athletic field built for organized league play. That's a different engineered product with its own certification requirements, and it's outside what a small local installer bids from a driveway. What we quote sits between a house lawn and a stadium: shared spaces that see heavy daily use but stay at a residential-to-light-commercial scale.</p>"),
        sec("What commercial turf costs, and how the timeline works",
            f"<p>We haven't found a reliable published per-square-foot figure for commercial turf that holds up across projects the way the residential range does; commercial jobs vary too much by surface, access and product grade to quote from a table. A commercial job gets priced from drawings or a site walk, and the drivers are consistent even when the number isn't: total square footage, what's underneath (compacted soil, an existing slab, or a rooftop deck that needs its own drainage system), the density and durability of the turf product for the traffic it'll see, and any permitting or insurance requirements tied to the size of the contract.</p>"
            + "<p>Timeline follows the same logic. An apartment complex's small dog park might take a few days, about the same as a large residential yard. A multi-building HOA's common-area lawn can run weeks once phasing is added so residents keep access throughout. A rooftop deck adds a design and engineering step before a crew ever shows up, because drainage and structural load have to be worked out first.</p>"),
        sec("What turf do dog parks, apartments and daycares use?",
            f"<p>Dog parks and apartment pet areas use a scaled-up version of {svc('pet', 'residential pet turf')}: fully permeable backing so urine passes through instead of pooling, no weed fabric underneath to trap odor, and usually a zeolite or antimicrobial infill sized for volume, since the surface serves every dog in the building rather than one household's. Daycares lean toward the same family as {svc('playground', 'playground turf')}: a soft, shorter pile, often paired with a shock pad under any climbing equipment sized to its fall height ({src('mightygrass-playground', 'playground turf specification guidance')}). A house lot's infill is limited by the state's turf standard to natural material; an apartment complex, a daycare and a dog park are commercial or multi-family sites, so that particular limit doesn't reach them and the product choice, crumb rubber under play equipment included, follows whatever the local site plan and playground safety rules call for.</p>"
            + "<p>Restaurant patios and office landscaping look closer to a residential lawn product, chosen more for appearance and easy sweeping than for the wear resistance a dog park needs. None of these are one product; the right spec depends on daily traffic volume more than on the type of business.</p>"),
        sec("Commercial turf specs by use",
            table("Turf builds for common commercial and shared-property applications", ["Site", "What it needs", "Why"],
                  [["HOA common-area lawn", "Residential-grade turf, higher face weight, mowed-lawn look", "Seen daily by many residents; has to hold up without looking worn"],
                   ["Apartment dog park", "Fully permeable backing, antimicrobial or zeolite infill, a flush-out zone", "Serves every resident's dog, not one household's, so odor control matters more"],
                   ["Restaurant patio", "Short, dense pile, fast drainage, easy to sweep", "High foot traffic in street clothes and hard-soled shoes, spills to manage"],
                   ["Rooftop deck", "Lightweight system, root-barrier-safe glue-down, engineered drainage board", "Structural load limits and waterproofing rule out a standard soil base"],
                   ["Daycare play yard", "Soft, shorter pile, shock pad sized to equipment fall height, no loose infill", "Young children are on it barefoot, and safety surfacing standards apply"]],
                  "Specs are quoted from the actual site and expected daily use; a small storefront planter and a 40-unit apartment dog run are not priced the same way.")),
        sec("How a commercial job gets built and quoted",
            steps([("Site walk or drawing review.", "We look at the actual surface, drainage direction, and access, or work from a set of plans if the site isn't built yet."),
                   ("Assess what's underneath.", "Soil, an existing slab, or a rooftop membrane each call for a different base and drainage plan before turf ever gets ordered."),
                   ("Size the drainage for the whole property.", "A commercial site's stormwater has to go somewhere without pushing water onto a neighboring unit or the property line."),
                   ("Match the product to actual daily use.", "A dog park for forty units sees more traffic in a week than a house yard sees in a year, and the spec reflects that."),
                   ("Phase the work if the property has to stay open.", "An apartment complex or a restaurant usually can't close during installation, so work gets sequenced in sections."),
                   ("Sign-off and a maintenance plan.", "The board, property manager or general contractor gets a written scope and a maintenance schedule sized to the traffic, not a homeowner's once-a-year routine.")])),
        sec("Florida heat, storms and rooftop drainage on commercial sites",
            f"<p>Heat behaves the same on commercial turf as anywhere else: full summer sun pushes the surface to 120 to 150°F, and shade structures matter more on a shared dog park that many families use through the afternoon than they do on one backyard. Afternoon storm drainage is a bigger design problem at commercial scale, because a badly graded shared lawn or a clogged rooftop drain doesn't just flood one homeowner's yard, it can send water toward a building or a neighboring unit, which is the same no-added-runoff principle behind the state's residential turf standard even though that rule itself doesn't reach commercial property.</p>"
            + f"<p>Large glass facades on multi-story buildings can concentrate reflected sunlight more than a single house window does, so we check nearby glass on any rooftop or courtyard job the same way we would near a pool. Irrigation is usually a separate system on a commercial site, watering planting beds rather than the turf area itself, but any zone that used to reach the turf footprint gets isolated the same way a house's would.</p>"),
        sec("HB 683, HOA common areas and permits for commercial turf",
            f"<p>This is the one place the state's new turf law doesn't reach. {a('/laws/florida-hb-683/', 'HB 683')} and the DEP rule behind it apply only to a single-family residential lot of an acre or less; an apartment complex, an HOA's own common area, a restaurant or a daycare is not that, so local zoning and landscape codes still fully apply with no state preemption to lean on. Check with the jurisdiction directly, since Osceola, Orange, Polk, Lake and Seminole counties don't all handle commercial landscape changes the same way; {a('/laws/permits/', 'the permit guide')} has what we've found for each.</p>"
            + f"<p>{a('/laws/hoa-rules/', 'F.S. 720.3045')}, the statute that protects a homeowner's fenced backyard from an HOA turf ban, is about an individual member's lot, not the association's own common property, so it doesn't apply to a clubhouse lawn or a shared entry median. That land follows whatever the association's own governing documents and local code say. Florida has no state license specifically for turf or landscape installation ({src('dbpr', 'DBPR license lookup')}), so a commercial contract usually rests on local business licensing and the insurance a property manager or GC requires in the bid.</p>"),
        sec("What goes wrong on a badly built commercial turf job",
            ul(["<strong>Residential base under commercial traffic.</strong> A base depth sized for one family's yard settles fast under daily use by forty apartment units.",
                "<strong>Wrong infill for a dog park.</strong> Standard silica infill under heavy daily dog use turns into an odor complaint from residents within a season.",
                "<strong>No engineered drainage plan.</strong> A patio or common area that ponds near an entrance becomes a liability, not just an eyesore.",
                "<strong>Rooftop work without the right underlayment.</strong> Skipping a proper root-barrier and waterproof layer on a rooftop install can void the building's roof warranty entirely."])),
        sec("Maintaining turf across a shared property",
            f"<p>Nobody on an HOA board or a property-management staff is going to brush a common-area lawn by hand the way a homeowner might, so commercial turf usually needs a standing service contract rather than occasional attention: scheduled power-brooming, an odor-control routine scaled to how many dogs actually use the park, and a leaf and debris cleanup pass ahead of any season that drops a lot of them. {svc('cleaning', 'Our cleaning and maintenance service')} covers that on a schedule sized to the property rather than to one yard.</p>"),
        sec("What do property managers ask when they search for the best commercial turf installer near me?",
            "<p>Boards and managers tend to ask a consistent short list before they'll sign: can the bid come from drawings rather than a guess, is the drainage plan spelled out in writing, is the product spec named with a face weight and backing type suited to commercial traffic rather than a homeowner-grade product, and can the crew phase the work so the property doesn't have to close. None of that is us claiming to be the top pick in Central Florida; it's the list any serious bidder should be able to answer without hesitating.</p>"
            + f"<p>{post('how-to-compare-artificial-turf-quotes', 'The same line-by-line comparison')} that works for a house lawn applies here, scaled up.</p>"),
        sec("Where we quote commercial work",
            f"<p>Managed properties in {city('kissimmee')}, {city('st-cloud')}, {city('celebration')} and {city('poinciana')} account for most of our commercial calls, along with apartment and daycare sites north into {city('hunters-creek')} and {city('lake-nona')}.</p>"
            + "<!--AUTO:service-cities-->"),
    ])
    faqs = [
        faq("Do you need architectural drawings to quote a commercial job?", "Drawings help and speed things up, but they're not required. A site walk works for smaller jobs like a single dog park or patio; larger multi-phase properties usually benefit from a plan set so drainage and access get worked out before a crew shows up."),
        faq("Can turf go on a rooftop deck?", "Yes, with a system built for it: lightweight base layers, an engineered drainage board, and glue-down installation that doesn't puncture the roof membrane. It's a different build than turf on soil and needs a structural and drainage review first."),
        faq("Does an apartment complex need a permit for a dog park?", "It depends on the jurisdiction and whether the work changes drainage or impervious surface on the site. Since HB 683's state standard doesn't cover commercial property, there's no blanket answer; check with the local permit office listed on our permit guide."),
        faq("How is commercial turf different from the turf on a house lawn?", "Mainly in traffic volume and what's underneath. A dog park or restaurant patio sees far more daily use than a house yard, so the base, drainage and infill are sized for that, and the surface is as often concrete or a rooftop deck as it is soil."),
        faq("Who maintains turf in a shared HOA common area?", "Usually whoever the association contracts for grounds maintenance, following a schedule the installer sets up rather than the once-a-year brushing a homeowner might do. We can build that maintenance plan into the original scope."),
        faq("Can a restaurant patio use turf without it getting slippery when wet?", "A short, dense, permeable turf drains fast and doesn't hold a film of water the way some hard patio surfaces can, but any wet outdoor surface still needs the same care a restaurant already gives its walkways."),
        faq("Does the state's new turf rule apply to our HOA common area or apartment complex?", "No. HB 683 and the DEP rule that implements it apply only to single-family residential lots of an acre or less. An HOA's own common area, an apartment complex, a restaurant or a daycare falls outside that law, and local zoning and landscape rules apply in full."),
        faq("What's the smallest commercial job you'll quote?", "We don't have a fixed cutoff. A single apartment dog run or a small office planting bed gets the same site walk and written scope as a larger property; very small jobs sometimes price closer to a residential minimum than a per-square-foot commercial rate."),
    ]
    return page("/commercial-turf/", "service",
                "Commercial Artificial Turf Installation in Kissimmee, FL",
                "Commercial artificial turf installation for HOAs, apartments, dog parks, daycares and patios in Kissimmee and Central Florida, quoted from a site walk.",
                "What Commercial Artificial Turf Installation Looks Like Here",
                capsule("Commercial artificial turf installation in Kissimmee and Central Florida covers HOA common areas, apartment dog parks, restaurant patios, rooftop decks and daycare play yards. Each job is quoted from drawings or a site walk rather than a flat per-square-foot rate, because traffic volume and what's underneath the turf change the build more than the address does."),
                body, faqs=faqs, service="commercial", crumbs=[("Services", "/services/")], crumb="Commercial",
                sources=["hb683", "fs125572", "dep-rule", "fs7203045", "fs7203075", "mightygrass-playground", "magnolia-pet-cost", "dbpr"],
                related=[("/pet-turf/", "Pet turf, the residential version of a dog park"), ("/playground-turf/", "Playground turf for a daycare or play area"),
                         ("/blog/artificial-turf-for-balconies-rooftops-and-condos/", "Turf for balconies, rooftops and condos"),
                         ("/blog/how-to-compare-artificial-turf-quotes/", "How to compare two turf quotes"),
                         ("/laws/florida-hb-683/", "What HB 683 does and doesn't cover"), ("/laws/permits/", "Permits by Central Florida jurisdiction")])


def _sports():
    body = "".join([
        sec("What we mean by sports and fitness turf",
            "<p>Sports turf installation here means backyard and small-facility surfaces built for a specific activity rather than general lawn use: a bocce court, a batting cage lane, a home-gym sled track, an agility strip for dog training, a patch of yard set up for casual backyard soccer. It's residential and small-commercial work, sized for a house lot, a home gym, a training studio or a small recreation area. We don't build full-size athletic fields for school or league play; those are engineered to a different specification and a different scale of bid entirely.</p>"
            + "<p>It suits a family that wants a real bocce court instead of a mowed strip that never rolls true, a household with a travel-ball kid who needs cage reps without a drive to a facility, or anyone setting up a home gym corner for sled work. It's a poor fit for anyone expecting a regulation-size court or field to fit a suburban backyard; most of what follows is about scaling a real sport down to a lot that size without losing what makes it play right.</p>"),
        sec("Sports turf specs: bocce, batting cages and home gyms",
            table("Sizing and turf specs for common home sports surfaces", ["Surface", "Size or spec", "Notes"],
                  [["Regulation bocce court", "86.92 ft × 13.12 ft (26.5 × 4 m)", f"Official size per the {ext('https://bocce.org/bocce-court-design/', 'U.S. bocce governing body')}; rarely fits a house lot at full length"],
                   ["Typical backyard bocce court", "About 60 ft × 12 ft", f"Common compromise length that still plays true ({ext('https://onelawn.com/bocce-ball-court-dimensions-size-guide/', 'backyard court sizing guide')})"],
                   ["Standard batting cage", "70 ft long × 14 ft wide × 12 ft tall", f"Full-size training cage dimension ({ext('https://coversports.com/resources/field-guides/batting-cage-dimensions-setup-guide', 'batting cage setup guide')})"],
                   ["Backyard batting cage", "35–70 ft long, 12–14 ft wide, about 12 ft tall", "Shorter lengths still give useful reps in a limited yard"],
                   ["Home gym / sled lane turf", "10–15 mm pile (about 3/8–5/8 in), 40 oz+ face weight, 50 oz+ for heavy sled work", f"Short, dense pile keeps sled resistance and speed consistent ({ext('https://www.roguefitness.com/gymturf', 'manufacturer sled-turf spec sheet')})"],
                   ["Padded multi-use gym turf", "5–8 mm foam backing under the pile", "Trades some sled speed for a surface that also works for stretching and bodyweight work"]],
                  "Bocce and cage dimensions are governing-body and manufacturer figures; a home version can run shorter without changing how it plays, as long as the width holds.")),
        sec("What turf works for each surface, and why it's not all the same product",
            f"<p>A bocce court needs a short, dense pile with a consistent, predictable roll, closer to a putting green surface than to a lawn; the {svc('putting', 'putting green build')} we already do shares more with a bocce court than either does with a backyard lawn. A batting cage lane needs a true, hard-compacted base underneath minimal-infill turf so a bounced ball behaves consistently, not a soft base that gives an unpredictable hop. A home-gym sled lane wants the shortest, densest pile of the group, sized by face weight rather than by looks, since the whole point is even sled resistance from one end to the other. An agility strip for dog training or a casual backyard soccer patch is closer to a normal residential lawn build and doesn't need a specialized spec at all.</p>"),
        sec("How we build a bocce court, batting cage pad or gym floor",
            steps([("Lay out and level over the full length.", "A bocce court gets laser-checked across its entire 60 to 87 feet; a court that's level at both ends but sags in the middle will pull every roll off-line."),
                   ("Frame or curb the edges.", "Bocce courts get a paver or timber curb so balls stay in play instead of rolling into the mulch; a batting cage gets its posts and netting frame set before turf goes in around them."),
                   ("Compact the base to a true, hard surface.", "A batting cage sits on the same washed, open-graded crushed rock any turf base uses, just run through more compaction passes than a lawn needs, since the ball wants a predictable bounce rather than a soft give."),
                   ("Run the turf grain the long way.", "On a bocce court, the fiber direction runs the length of the court so the roll behaves the same in both directions."),
                   ("Glue gym and lanai floors, seam outdoor courts.", "A home-gym sled lane over an existing garage or lanai slab gets glued the same way pool-deck turf does; an outdoor bocce court over soil gets seamed over a compacted rock base, without packing the sand beneath it so hard that it stops draining."),
                   ("Keep seams out of the lane.", "Seams are placed to the side of a sled track or a cage's ball path rather than down the middle, so the join doesn't affect the surface where it matters most.")])),
        sec("What it costs and how the timeline works",
            "<p>There's no single per-square-foot number for sports turf the way there is for a residential lawn, because a 60-foot bocce curb, a batting cage frame and netting, and a glued gym floor are different scopes of work on a small footprint. We quote from the actual dimensions and the base condition: whether it's new ground that needs excavating and a curb built, or an existing garage or lanai slab that just needs cleaning and gluing. A short home-gym lane over an existing slab is often the fastest of the group, sometimes a single day; a full bocce court with a curb and full-length grading takes longer despite its narrow width, because the base has to be right over every foot of that 60-plus-foot run.</p>"),
        sec("Heat, rain and reflection on outdoor sports surfaces",
            f"<p>An outdoor bocce court or backyard soccer patch in full sun gets just as hot as any lawn turf, 120 to 150°F at the surface in summer ({src('magnolia-heat', 'measured Florida readings')}), which matters more here because bocce games and pickup soccer run long in the afternoon rather than a quick walk across the yard. A shade sail over a court is worth the cost if it sits in full sun most of the day. A batting cage's netting provides some shade on its own. Drainage follows the same principle as any turf: perforated backing passes water faster than a Central Florida storm delivers, but the base under a bocce curb still needs the same grading away from the house that any yard needs.</p>"
            + f"<p>A home-gym sled lane installed near a west-facing sliding door carries the same reflected-glare risk as turf near a pool; {post('can-artificial-turf-melt', 'turf can soften from concentrated window reflection')}, so we check nearby glass before finishing an indoor-adjacent lane. Outdoor courts and lanes on a house lot follow the same capped-irrigation rule as any residential turf: an in-ground system can't be used to water synthetic turf once it's down.</p>"),
        sec("HOA, permit and code notes for backyard sports surfaces",
            f"<p>{a('/laws/florida-hb-683/', 'The state’s HB 683 standard')} applies to any turf on a single-family lot of an acre or less, a home bocce court and sled lane included: infill has to be a natural material such as silica or zeolite rather than rubber crumb, the base underneath has to be washed rock so it stays permeable, and the turf stays outside a tree's drip line without an arborist's sign-off and at least 10 feet from a pond or canal's edge unless a seawall or bulkhead already runs along it, which matters on golf-adjacent lots in 55-plus communities where a bocce court often goes in near a water feature. A small commercial training studio or sports facility isn't a single-family lot, so that standard doesn't reach it and local code governs instead. A batting cage's posts and netting are a structure separate from the turf underneath them, and some HOAs review a cage frame differently than they'd review turf alone, so check both. {a('/laws/hoa-rules/', 'Florida’s protection for a fenced backyard')} not visible from the street covers turf itself but not necessarily a tall netting structure, and {a('/laws/permits/', 'the permit guide')} has jurisdiction-specific detail.</p>"),
        sec("What goes wrong with a bad sports-surface install",
            ul(["<strong>A bocce court leveled only at the ends.</strong> A sag in the middle of a 60-plus-foot run pulls every roll off-line, and it's expensive to fix after the fact.",
                "<strong>A batting cage base built like a lawn.</strong> A soft, loosely compacted base under cage turf gives an inconsistent bounce that undoes the point of practicing on a true surface.",
                "<strong>Gym turf glued without enough adhesive.</strong> A sled lane that lifts at the edges under repeated pushing is a trip hazard, not just a cosmetic problem.",
                "<strong>Loose infill under a home gym floor.</strong> Infill that migrates from a garage or lanai lane tracks into the house on shoes and bare feet."])),
        sec("Caring for a home sports surface",
            f"<p>Brush a bocce court's lane after use so pollen and debris don't slow the roll, especially during oak leaf drop, and hose it down periodically for the same reason. Trim any grass or mulch that's crept over a batting cage's turf edge where the frame meets the ground. Check a glued gym lane's edges after heavy sled sessions and re-glue anything that's started to lift before it becomes a bigger repair. {svc('repair', 'Seam and edge repairs')} on any of these surfaces are usually straightforward if they're caught early rather than after months of use.</p>"),
        sec("How do you find the best sports turf installer near you for a bocce court or batting cage?",
            f"<p>Ask whether the installer has actually leveled a long, narrow run like a bocce court before, since that's a different skill than a rectangular lawn. Ask what base they'd compact under a batting cage and why it's firmer than a lawn base. Ask for the turf's pile height and face weight in writing, not just a sample that looks similar to another product. Those specifics matter more than a general claim about being the top choice locally, and they're the same questions that separate a court that plays true from one that doesn't. {a('/compare/nylon-vs-polyethylene-vs-polypropylene-turf/', 'The fiber comparison')} and {post('artificial-turf-glossary', 'this glossary of turf terms')} explain the vocabulary a spec sheet uses.</p>"),
        sec("Where we build home sports surfaces",
            f"<p>Bocce courts and home-gym lanes come up most often in {city('kissimmee')}, {city('celebration')} and the 55-plus and golf communities around {city('davenport')}; batting cages are a common request from families in {city('hunters-creek')} and {city('st-cloud')}.</p>"
            + "<!--AUTO:service-cities-->"),
    ])
    faqs = [
        faq("Can you build a regulation bocce court in a backyard?", "Only on a lot with room for the full 86.92 by 13.12 feet, which is uncommon on a standard house lot. Most backyard courts run about 60 feet long instead, which plays true as long as the width and the base are right."),
        faq("Does a batting cage need turf, or can I use gravel or dirt?", "Turf gives a consistent, predictable bounce that gravel and bare dirt don't, and it stays usable through Florida's rainy season without turning to mud. The base underneath matters as much as the turf itself for how the ball plays."),
        faq("What's the difference between padded and unpadded gym turf?", "Unpadded turf gives the truest, fastest surface for sled work and sprint lanes. Padded turf adds a foam backing, usually 5 to 8 mm, that trades some sled speed for comfort during stretching and bodyweight exercises, which suits a multi-use space better than a dedicated sled lane."),
        faq("Can turf handle a weighted sled every day?", "Yes, when it's specified for it: a dense, short pile with a face weight of 50 ounces or more per square yard and a base or backing built to take repeated dragging without shifting."),
        faq("Do you build full soccer or football fields?", "No. That's an engineered surface built to a league or school specification, and it's a different scale of project than we bid. We build backyard-size surfaces for casual play, agility work and home training."),
        faq("Can a dog-agility lane share the same turf as the rest of the lawn?", "Usually yes for casual training. A dedicated agility surface for frequent, hard use benefits from the denser, more durable turf we'd use for pet areas, but a backyard lawn works fine for occasional practice."),
        faq("How long does a bocce court or batting cage turf install take?", "A home-gym lane over an existing slab can be a single day. An outdoor bocce court with a new curb and full-length grading usually takes longer than its narrow footprint suggests, because the base has to be right over the whole run."),
        faq("Does infill matter for a sled track?", "Less than it does for a lawn. Sled lanes are often built with minimal or no loose infill so the sled glides on the pile itself rather than on sand, which also keeps infill from tracking into the house."),
    ]
    return page("/sports-turf/", "service",
                "Sports Turf Installation in Kissimmee, FL",
                "Sports turf installation for home bocce courts, batting cages, sled lanes and agility strips in Kissimmee, with real dimensions and specs, not stadium turf.",
                "Sports Turf Installation for Backyard Courts, Cages and Sled Lanes",
                capsule("Sports turf installation for homes and small facilities around Kissimmee covers bocce courts, batting cage lanes, home-gym sled tracks and agility strips, each built to its own base and pile spec rather than a standard lawn build. We work at residential and small-commercial scale, not full athletic fields, and quote from the actual dimensions on site."),
                body, faqs=faqs, service="sports", crumbs=[("Services", "/services/")], crumb="Sports & fitness",
                sources=["magnolia-heat", "sgw-faq", "hb683", "dep-rule", "fs7203045",
                         ("U.S. bocce court design and dimensions", "https://bocce.org/bocce-court-design/"),
                         ("OneLawn — bocce ball court dimensions and size guide", "https://onelawn.com/bocce-ball-court-dimensions-size-guide/"),
                         ("CoverSports — batting cage dimensions setup guide", "https://coversports.com/resources/field-guides/batting-cage-dimensions-setup-guide"),
                         ("Rogue Fitness — GymTurf sled and sprint-lane turf spec sheet", "https://www.roguefitness.com/gymturf")],
                related=[("/putting-greens/", "Putting greens, the closest build to a bocce court"), ("/pet-turf/", "Pet turf for an agility or dog-training lane"),
                         ("/blog/artificial-turf-glossary/", "Turf terms: face weight, pile height and infill"),
                         ("/blog/artificial-turf-on-a-slope/", "Installing turf on a sloped yard"),
                         ("/compare/nylon-vs-polyethylene-vs-polypropylene-turf/", "Nylon vs. polyethylene vs. polypropylene turf"),
                         ("/artificial-turf-cost/", "Full turf cost guide with tables")])


def get_pages():
    return [_pool(), _str(), _commercial(), _sports()]
