# -*- coding: utf-8 -*-
"""Service pages: turf & pavers, turf repair, turf cleaning, turf replacement."""
from _data import PRICE_DATE
from _helpers import page, capsule, sec, table, faq, steps, cta, a, svc, city, post, src, ext, price, photo

TURFRESH_REPAIR = "https://turfresh.com/blog/artificial-turf-repair-vs-replace/"
INSTALLARTIFICIAL_LA_REPAIR = "https://www.installartificial.com/how/repair-artificial-grass-in-los-angeles-cost-and-methods"
SPARKLYTURF_CLEAN = "https://sparklyturf.com/artificial-turf-cleaning-cost/"
IFAS_LOVEBUGS = "https://blogs.ifas.ufl.edu/sarasotaco/2020/05/20/lovebugs-the-bug-we-love-to-hate/"
IFAS_LIVEOAK = "https://nfrec.ifas.ufl.edu/live-oak-info/"
TOTALTURF_DISPOSAL = "https://totalturfsupply.com/dispose-synthetic-grass/"
WASTEADV_RECYCLE = "https://wasteadvantagemag.com/ways-you-can-recycle-artificial-turf/"


# ---------------------------------------------------------------- 1. turf & pavers
def pavers_page():
    body = "".join([
        sec("Where turf between pavers works, and where it doesn't",
            "<p>A paver and turf installation succeeds or fails at the joint between the two materials, not inside either one alone. Turf between pavers earns its keep in specific spots: driveway ribbon turf down the center where tires never track, stepping stone turf filling the gaps between treads on a path through the yard, grid pavers with artificial grass over a parking pad, or a checkerboard patio alternating paver squares with turf squares off the lanai. It reads as intentional, not as a lawn that failed.</p>"
            + f"<p>It also solves a problem Kissimmee homeowners run into with real grass in these spots: a strip a few inches wide between pavers dries out fast in full sun, and Toho Water Authority's two-day watering schedule rarely keeps it alive. A wide-open area next to the hardscape is a different job. A 600 sq ft side yard is cheaper and simpler as one piece of {svc('residential', 'lawn turf')} than as ten narrow ribbons, so we reserve the paver-and-turf approach for the spots the hardscape pattern actually creates. Driveway wheel paths are a poor fit for the same reason turf ribbons work everywhere else: turf laid where tires roll gets crushed and stained with oil, so the green strip belongs in the center or along the border, never in the tracks.</p>"),
        photo("turf-between-pavers", "Turf ribbons between porcelain pavers set on the diagonal. The strips are cut to the joint and trimmed so the pile sits a touch above the paver face."),
        sec("Four ways we lay turf and pavers together",
            "<p>The layout decides almost everything else about a job: strip width, how the edge gets held, and where the water goes. These four patterns cover most of what comes up in Osceola and south Orange County yards.</p>"
            + table("Turf-and-paver layouts and their build notes",
                    ["Layout", "Typical width", "Edge treatment", "Drainage note"],
                    [["Driveway ribbon turf", "8–18 in", "The paver course on both sides doubles as the nailing edge", "Crowned slightly so runoff sheds toward the paver joints, not the garage"],
                     ["Stepping stone turf path", "4–8 in between treads", "Tucked tight to the paver's chamfered edge, nailed into the base beyond it", "Base has to drain as fast as the turf or the strip becomes a sponge between dry pavers"],
                     ["Grid pavers with artificial grass", "2–4 in cell openings", "No separate edge; the paver cell holds the turf plug in place", "Built for infiltration, so the base under the cells stays open rather than compacted solid"],
                     ["Checkerboard patio", "Full paver-size squares, 12–24 in", "Bender board or a mortared edge around each turf square", "Each square carries its own slight crown so water doesn't pool in the pile"]],
                    "Widths are typical for residential jobs; a site visit sets the exact number against the paver pattern you have or are choosing.")),
        photo("rooftop-amenity-deck", "A wide turf field meeting large-format pavers on a rooftop deck: one straight seam, no edging strip, the paver course itself holds the turf edge."),
        sec("One layout, two base materials",
            f"<p>Pavers and turf don't actually want the same base material, which surprises people expecting one uniform layer under everything. Pavers sit on a dense-graded aggregate, sized to lock together tight enough to carry a tire's point load without shifting. Turf's base has to do close to the opposite: {src('dep-rule', 'the state synthetic turf standard')} requires a washed, open-graded crushed rock or crushed concrete subgrade under turf, sized and washed so fines don't bind it into a crust that stops water from passing through. Run one material under the other and either the turf floods or the paver bearing surface goes soft.</p>"
            + "<p>What stays continuous is the layout, not the aggregate: one finished grade set for the whole area before either material goes down, one drainage plan, and an edge restraint that ties the two base types together at the joint instead of leaving a gap.</p>"
            + steps([("One grade, cut once.", "We set the finished elevation for the whole area before either material goes down, so the paver's dense-graded base and the turf's washed, open-graded base meet at the same finished height."),
                     ("Two base materials, kept separate.", "Paver zones get a dense-graded aggregate compacted for bearing; the turf strip gets a washed, open-graded crushed rock or crushed concrete base per the state standard, with a fabric or edge to keep the two from migrating into each other."),
                     ("Edge restraint goes in first.", "A paver edge restraint, a bender board, or the paver course itself is set and checked for line before a single roll of turf gets cut."),
                     ("Turf is cut long, then trimmed tight.", "Strips are cut a little wide and trimmed to the paver edge on site, because even a good hardscape job is never perfectly straight."),
                     ("Fastened into the base, never into the paver.", "Nails or adhesive anchor into the turf's own base material beside the paver, so the turf can be lifted for a repair without disturbing the hardscape."),
                     ("Infill matched to the strip width.", "A narrow ribbon gets a slightly heavier rate of clean silica sand or a coated sand so the blades stand up instead of leaning flat toward the paver's shade line.")])),
        sec("How turf between pavers is priced",
            f"<p>Turf between pavers doesn't fit a clean per-square-foot number, because most of the cost is edge, not area. The turf itself still falls in the usual Central Florida range, {price('residential')} a square foot installed, but a paver-and-turf job prices toward the top of that range or gets quoted as one flat price for the whole strip. A crew still shows up, compacts a base and sets an edge restraint whether the ribbon covers 400 square feet or 40.</p>"
            + "<p>What pushes the number up: narrow widths, which mean more linear feet of edge per square foot of turf; curves that follow a paver pattern instead of a straight run; matching an existing paver color and joint width exactly; and coordinating a schedule with a separate hardscape crew when the pavers aren't part of the same job. What holds it down: a straight run, a strip wide enough to read as its own material rather than a sliver, and pavers that are already in and level so we're not correcting someone else's grade first.</p>"),
        sec("What Florida sun, storms and sand do to a paver-and-turf job",
            f"<p>Pavers and turf don't handle heat the same way, and that matters when they sit inches apart. Concrete and clay pavers hold the sun's heat and release it slowly, so the blades along that edge often run hotter than the middle of an open lawn; a light paver color and a quick hose rinse bring both surfaces down together ({src('horsemans-heat', 'installer heat measurements')}). Central Florida's summer storms, which can drop one to three inches of rain in an hour, are the bigger risk: a narrow strip with a paver lip on both sides has nowhere to shed water sideways, so the crown and the base's drainage matter more here than on a wide-open yard.</p>"
            + "<p>Kissimmee's fine native sand settles unevenly under two different base materials compacted to two different specs, which is why the subgrade underneath both gets graded and firmed the same way before either aggregate goes down, rather than treating one side as an afterthought once the other is finished. The state standard also caps how hard that native soil can be compacted, since packing it too tight under the turf hurts percolation. Near a live oak, root flare can lift a paver course and the turf edge riding against it at the same time; if the layout falls inside the tree's drip line, the state's synthetic turf standard requires a certified arborist to sign off before we build there.</p>"),
        sec("Permits, HOA review and the driveway apron",
            f"<p>A driveway ribbon or a front-walk path is, by definition, visible from the street, which puts it outside the protection homeowners get under F.S. 720.3045; that statute only stops an HOA from restricting turf that can't be seen from the frontage or a neighboring lot ({src('fs7203045', 'the statute text')}). In communities such as {city('celebration')} or {city('reunion')}, expect an architectural review application for a front-yard paver-and-turf project even though a fenced backyard version of the same idea might not need one. {a('/laws/hoa-rules/', 'What a Florida HOA can and can not restrict')} covers that split in more detail, and the {a('/laws/permits/', 'permit guide')} lists what each local office asks for when pavers and drainage are both part of the scope.</p>"),
        sec("What a rushed paver-and-turf job looks like two summers later",
            "<p>The tell is almost always at the edge. Turf nailed straight into the paver instead of into the base pulls the fastener loose the first time the paver shifts on its own bedding sand, and the strip lifts in a wave along one side. A joint width that wasn't held consistent looks fine from the porch and uneven from the driveway, especially where two crews worked from two different chalk lines. Infill that wasn't matched to a narrow strip washes into the paver joints during the rainy season, leaving the turf thin and the joints stained.</p>"
            + f"<p>A base compacted only under the turf, with loose sand left under the pavers, settles at a different rate, so the paver edge ends up a quarter-inch proud of the turf within a year, a lip that catches a stroller wheel or a bare foot. {post('install-artificial-turf-over-concrete-pavers-or-grass', 'This guide')} covers the same failure mode where turf meets a hard surface generally.</p>"),
        sec("Keeping the joints clean",
            f"<p>Rinse the strip with a hose along with the rest of the yard; a paver-and-turf ribbon collects more windblown grit than an open lawn because it's narrow and often runs along a hard edge that channels debris. Brush the pile against the grain a few times a year so it doesn't lie flat toward the paver, the direction both water and foot traffic push it. Keep an eye on the paver joints themselves separately, since the sand there is a different material with its own refresh schedule than the turf's infill.</p>"
            + f"<p>After a named storm, walk the full edge. A lifted corner caught early is a small {svc('repair', 'repair')}, and the state's anchoring requirement exists precisely because wind gets under an unanchored edge before rain does.</p>"),
        sec("Who is the best turf and paver installer near me?",
            f"<p>That's the right question to ask before signing anything, and the honest answer is that you can't tell from a finished photo. Ask three things: whether the quote lists one compacted base spec for the whole area instead of a vague \"standard prep,\" whether the edge restraint is named outright (paver, bender board or spike edge) rather than assumed, and whether the crew has actually tied turf into an existing paver layout before, since that's a different skill from either trade alone. A contractor who answers all three without hesitation has likely done it more than once.</p>"
            + cta("Get a measured quote", "Tell us the paver pattern and where the strip runs, and we'll work out the base and edge details before we quote it.")),
    ])
    faqs = [
        faq("Can turf go between pavers I already have, or do the pavers have to be new?", "Existing pavers work fine as long as they're level and the joint is at least a couple of inches wide. We check the paver's bedding for firmness first; if it's already settling, that gets corrected before turf goes in next to it, or the fix won't last."),
        faq("How wide does a turf strip between pavers need to be?", "There's no hard minimum, but strips under about three inches are hard to seam cleanly and tend to look like caulk rather than grass. Four to eight inches reads as an intentional design line; anything wider starts behaving like its own small lawn."),
        faq("Will turf between pavers fade a different shade than a nearby lawn?", "It can, if the two are different products or ages. We try to match pile height and color family when a paver strip sits near an existing turf lawn, though a strip installed years apart from the lawn will show some difference the way any two turf ages do."),
        faq("Does turf between pavers need its own drainage?", "It needs to drain into the same overall plan the pavers do, even though the aggregate under the turf is a different, washed and open-graded material than the paver base. Both are graded off the same layout, so water moving through the turf has somewhere to go instead of pooling against a paver lip."),
        faq("Can turf go inside grid pavers on a driveway that carries car weight?", "Yes, that's what grid pavers with artificial grass are built for. The rigid paver grid carries the wheel load, and the turf plug inside each cell sits on the same washed, open-graded base the state standard requires for any turf, so the cell stays permeable instead of packing solid under traffic."),
        faq("How do you keep infill from washing into the paver joints?", "Matching the infill rate to the strip width helps, along with keeping the turf's finished height slightly above the paver surface so water sheds off the blades before it reaches the joint sand. On very narrow ribbons we sometimes skip infill and rely on a denser, self-standing pile instead."),
        faq("Is a paver-and-turf driveway ribbon covered by the same Florida turf law as a backyard lawn?", "The state's synthetic turf standard applies to the material and how it's installed regardless of where on the lot it sits. The HOA-visibility statute is what changes: a driveway ribbon is visible from the street, so it doesn't get the same protection from architectural review that a fenced backyard strip would."),
    ]
    return page("/turf-and-pavers/", "service",
                "Turf Between Pavers in Kissimmee, FL",
                "Turf between pavers in Kissimmee: one shared layout, joint width, edge restraint and drainage for ribbons, stepping stones and checkerboard patios.",
                "Turf between pavers in Kissimmee, Florida",
                capsule(f"Turf between pavers ties a driveway, walkway or patio together with a green line instead of loose rock or bare joint sand. In Kissimmee the turf itself still runs the usual {price('residential')} a square foot, but a narrow strip prices near the top of that range because the edge work, not the area, takes the crew's time. Most jobs finish in a day."),
                body, faqs=faqs, service="pavers", image="turf-between-pavers", crumbs=[("Services", "/services/")], crumb="Turf & pavers",
                sources=["fs7203045", "dep-rule", "marathon-pr", "sgw-faq", "horsemans-heat", "attampa-cost"],
                related=[("/artificial-grass-installation/", "Residential turf installation"), ("/pool-turf/", "Turf around pools and lanais"),
                         ("/compare/turf-vs-pavers-vs-rock-side-yard/", "Turf vs. pavers vs. rock, compared"),
                         ("/blog/install-artificial-turf-over-concrete-pavers-or-grass/", "Turf over concrete, pavers or grass"),
                         ("/blog/artificial-grass-for-shady-side-yards/", "Turf for shady side yards"),
                         ("/artificial-turf-cost/", "Full turf cost guide")])


# ---------------------------------------------------------------- 2. turf repair
def repair_page():
    diag_rows = [
        ["Wrinkle or wave in the middle of a panel", "Base shifted, or the turf was never stretched drum-tight during the original install", "Lift, re-stretch, re-secure the edge; no iron or weight, that only hides it for a season"],
        ["Open or separating seam", "Adhesive skinned before it bonded, often from gluing over a damp or dusty base", "Cut back to a clean stitch row, reseam with tape and adhesive under dry conditions"],
        ["Lifted or curling edge", "Nails pulled loose, or wind got under an edge that wasn't anchored tightly", "Re-nail into solid base at tighter spacing, or switch to an adhesive edge where nails keep failing"],
        ["Burn or melt patch", "Reflected sun off a low-E window; turf's polyethylene softens around 175–200°F", "Cut out the affected section and set a matched patch; the window itself may need a film or an awning"],
        ["Flattened turf in a traffic lane", "Foot traffic packed the blades down and pressed the infill flat", "Power broom against the grain; replace the section if the backing itself is crushed, not just the fiber"],
        ["Water standing after rain", "The base settled or never had enough slope; not a turf-drainage problem", "Lift the area, add and recompact base to restore the 1–2% grade away from the house"],
        ["Torn seam or urine-burned patch near a gate", "Digging at an open seam, or acidic urine pooling in one repeated spot", f"Reseam or patch the section; for recurring odor, {svc('cleaning', 'a cleaning visit')} with an enzyme treatment usually handles the rest"],
    ]
    body = "".join([
        sec("When a repair makes sense, and when it doesn't",
            "<p>Artificial turf repair covers seam repair, turf wrinkles, lifted edges, a burn or melt patch, flattened turf in a traffic lane, a drainage fix, and pet damage near a gate or a dig spot. A repair is the right call when the problem is local: one seam open along a few feet, a corner that lifted after a storm, a scorch mark under a west-facing window. The rest of the lawn is doing its job, so there's no reason to replace it. We also repair turf other companies installed, which is most of what we see; the original crew doesn't have to still be in business, or even identifiable, for a seam to get fixed.</p>"
            + f"<p>It's not worth patching when the turf is twelve to fifteen years old and showing wear everywhere, not only at the trouble spot, because new turf never quite matches sun-faded fiber, and paying repair labor toward a lawn that needs to come out soon anyway is money spent twice. The other sign it's time to stop patching: the same spot failing a second or third time, which usually means the base underneath is the real problem and no amount of reseaming fixes that. {svc('replacement', 'Turf replacement')} covers what that decision looks like.</p>"),
        sec("How do you fix wrinkles, open seams and flattened turf?",
            "<p>Wrinkles come from a base that shifted or turf that was never stretched tight, and the fix is to lift the panel, pull it drum-tight, and re-secure the edge, not to weigh the bump down. Open seams are cut back to a clean stitch row and rejoined with seam tape and adhesive. Flattened turf is brushed hard against the grain; if the backing itself has crushed, that section gets replaced rather than just brushed.</p>"
            + table("Common turf problems, likely cause and the fix", ["Symptom", "Usual cause", "Typical fix"], diag_rows)),
        sec("How a repair visit actually goes",
            "<p>Here's the sequence on a typical call, whether it's a small patch or a wider re-stretch.</p>"
            + steps([("You send photos or we come look.", "A phone photo of a wrinkle or an open seam is usually enough to quote a range before anyone's on site."),
                     ("We find the cause, not just the symptom.", "Lifting a corner shows whether the base underneath is still solid or whether it's soft, washed out or root-heaved."),
                     ("We cut to a clean edge.", "Patches and reseams are trimmed back to a stitch row on all sides so the tape has a straight line to bond to, not a ragged cut."),
                     ("Grain runs the same direction.", "Replacement turf, even from the same product line, gets checked against the existing pile direction before it's seamed in."),
                     ("Seams cure under weight.", "Sandbags or boards hold a fresh seam flat while the adhesive sets, usually a few hours depending on temperature and humidity."),
                     ("Infill goes back and we walk the perimeter.", "We top up infill over the repair and check the rest of the edge, since one storm-lifted corner is often not the only one.")])),
        sec("What artificial turf repair costs",
            f"<p>Artificial turf repair is priced by scope, not by the square footage of the whole lawn, and we haven't found a published Central Florida-specific price survey for it as of {PRICE_DATE}. What is published, from national installer cost guides, gives a reasonable frame: a small seam re-glue or patch under 20 sq ft runs roughly $350 to $950, a larger patch with matched turf and a full infill refresh runs $850 to $2,400, and a full re-stretch and re-nail on a lawn lifting across a wide area runs $1,800 to $5,500 ({ext(TURFRESH_REPAIR, 'a 2026 repair-versus-replace cost breakdown')}). A single-issue service call in most U.S. markets lands around $500 to $1,000 for a few hours of labor and materials ({ext(INSTALLARTIFICIAL_LA_REPAIR, 'a Los Angeles repair cost guide')}).</p>"
            + "<p>Those are market ranges, not our quote. Repairs here carry a minimum service charge, because a truck, tools and scrap turf show up whether the fix takes twenty minutes or two hours. Send photos first and we'll tell you which tier it's likely to land in before scheduling a visit.</p>"),
        sec("Why Florida turf fails the way it does",
            f"<p>Heat does most of the damage that ends up as a repair call. Full summer sun pushes turf past 150°F at the surface and can pass 160°F ({src('horsemans-heat', 'installer heat measurements')}), and the expansion and contraction through that swing is what pulls a marginal seam apart over a year or two; a reflected hot spot off a west-facing window can push a small area past the point where the blades soften and melt. {post('can-artificial-turf-melt', 'This post')} goes deeper on the window-glare problem specifically.</p>"
            + "<p>Storm season adds the other half: wind gets under an edge that wasn't anchored tightly, and heavy rain finds any low spot where the sandy base has settled, common on Kissimmee's fine, loose native soil after a few wet seasons. Live oak roots are the quieter cause, lifting a seam from below over a year or two as a root grows under turf laid too close to the trunk. None of this is a defect in the turf material; it's a base or edge problem that shows up as a turf problem.</p>"),
        sec("Does a repair need a permit or HOA sign-off?",
            f"<p>Almost never. A repair restores what was already there rather than changing the footprint or the material, so it doesn't typically trigger the review a first-time installation would. The exception is a repair that also changes something visible from the street, such as re-anchoring an edge with a different border material; in a community with strict guidelines, mention that change when you tell the board the lawn is being worked on. {a('/laws/hoa-rules/', 'What a Florida HOA can and can not restrict')} explains where that line sits, and the state standard requiring anchored edges and seams on a new install ({src('dep-rule', 'Rule 62-308.100')}) is a reasonable bar for judging whether a repair was done right.</p>"),
        sec("What a bad repair looks like next season",
            "<p>A patch that doesn't match is the most obvious failure: a different lot, a different sun exposure, or a different manufacturer's green shows up as a visible rectangle for years, because turf doesn't blend the way a lawn does. Less obvious until it fails again: a seam reglued over a base that was never cleaned or dried, which looks fine on install day and opens again within a season because the adhesive skinned before it bonded.</p>"
            + "<p>Nails driven back into the holes they pulled out of don't hold any better the second time. And a wrinkle that gets ironed flat or weighted down instead of re-stretched will be back by the next hot week, because the extra material is still there, just hidden instead of removed.</p>"),
        sec("After the repair",
            f"<p>Keep foot traffic light on a fresh seam for about a day while the adhesive fully cures. Brush the repaired section against the grain once it's set so it blends with the surrounding pile, then give it a hose rinse to settle the new infill. Walk the yard after the next named storm the way you would any other time; a repair holds up to the same wind and rain as the rest of the lawn, no better and no worse. If the same spot fails twice, that's the signal to ask about the base rather than request a third patch. {post('does-homeowners-insurance-cover-artificial-turf', 'This guide')} covers when a storm-related repair might be a claim instead of an out-of-pocket fix.</p>"),
        sec("Who is the best turf repair contractor near me?",
            "<p>Ask that question with a follow-up: will they explain why the problem happened, not just what they'll do to hide it? A contractor worth hiring lifts the damaged area, shows you the base, and tells you whether the cause is fixed or just covered. Ask whether they'll repair turf they didn't install, since a surprising number of companies won't touch another crew's work, and ask for the minimum charge up front so a twenty-minute fix doesn't turn into a surprise invoice.</p>"
            + cta("Get a repair quote", "Send photos of the seam, wrinkle or spot and we'll tell you what tier it's likely in before we schedule a visit.")),
    ])
    faqs = [
        faq("Can a wrinkle be fixed without replacing the whole lawn?", "Yes, in almost every case. The panel is lifted, re-stretched drum-tight and re-secured at the edge. Replacing the whole lawn over a wrinkle is rarely necessary unless the same panel has wrinkled more than once, which usually points to a base problem instead of a stretching problem."),
        faq("Why did a seam open only two or three years after installation?", "Most early seam failures trace back to adhesive applied over a base that was damp, dusty or not fully cured, which lets the bond look fine on install day and let go later. Foot traffic across a fresh seam before the adhesive sets can cause the same result."),
        faq("Can you match a repair patch to turf that's faded from years of sun?", "Not perfectly. New turf is always a shade greener than several summers of UV exposure have left the surrounding lawn, so a patch on an older lawn stays visible, at least for a while. It solves the functional problem even where it doesn't disappear visually."),
        faq("Is a lifted turf edge after a storm urgent?", "Worth addressing within a week or two. Wind and rain both work under a lifted corner and can widen the problem, and standing water at a lifted seam breaks down the adhesive faster than a dry edge would."),
        faq("Will you repair turf that another company installed?", "Yes. Most repair calls we get are on lawns we didn't originally build. What matters is whether the base underneath is sound enough to repair; if it isn't, we'll say so instead of patching over it."),
        faq("What's the smallest repair job you'll take?", "A single seam or a patch under a few square feet, though it still carries the minimum service charge that covers the trip and setup. Text a photo and we'll tell you what to expect before booking a visit."),
        faq("How long does a typical repair visit take?", "A single seam or small patch is usually a two- to four-hour visit including cure time under weight. A full re-stretch of a lifting panel, or a repair that needs a discontinued turf matched, can take a full day."),
    ]
    return page("/turf-repair/", "service",
                "Artificial Turf Repair in Kissimmee, FL",
                "Artificial turf repair in Kissimmee: fixes for wrinkles, open seams, lifted edges and melt spots, with 2026 market-range pricing and repair-vs-replace signs.",
                "Artificial turf repair in Kissimmee, Florida",
                capsule("Artificial turf repair fixes the specific thing that failed, not the whole lawn: a wrinkle, an open seam, a lifted edge, a burn spot from window glare, or a low area that holds water after a Kissimmee storm. Most single-issue repairs are a half-day visit. Published national ranges run roughly $350 to $2,400 depending on scope; a firm number follows photos or a site visit."),
                body, faqs=faqs, service="repair", crumbs=[("Services", "/services/")], crumb="Turf repair",
                sources=["dep-rule", "marathon-pr", "horsemans-heat",
                         ("TurfResh — repair or replace artificial turf, a 2026 cost breakdown", TURFRESH_REPAIR),
                         ("InstallArtificial — cost to repair artificial grass in Los Angeles, 2026", INSTALLARTIFICIAL_LA_REPAIR)],
                related=[("/turf-cleaning/", "Turf cleaning and pet-odor treatment"), ("/turf-replacement/", "When to replace instead of repair"),
                         ("/blog/can-artificial-turf-melt/", "Can artificial turf melt?"), ("/blog/artificial-turf-hurricane-flooding/", "Turf after a hurricane or flood"),
                         ("/blog/does-homeowners-insurance-cover-artificial-turf/", "Does insurance cover turf repair?"), ("/artificial-turf-cost/", "Full turf cost guide")])


# ---------------------------------------------------------------- 3. turf cleaning
def cleaning_page():
    cal_rows = [
        ["Weekly (pet yards), every other week otherwise", "Hose rinse and a quick debris check", f"Central Florida heat turns urine into odor fast; {src('dep-rule', 'Rule 62-308.100')} bars using an in-ground irrigation system on turf, so every rinse here is by hose"],
        ["Monthly", "Power broom against the grain, check infill depth", "Regular traffic and lovebug season, roughly April–May and again August–September in Florida, mat the pile down and leave residue that needs brushing out"],
        ["Twice a year, spring and fall", "Deep clean: sanitizing rinse, infill top-up, edge and seam check", "Timed around the live oak leaf drop in late winter into early spring and just ahead of the June–September rainy season"],
        ["After named storms or heavy pollen weeks", "Rake off debris, rinse the pollen film, check for standing water", "Afternoon storms can drop one to three inches an hour; spring pollen coats turf in a yellow film a plain rinse lifts"],
    ]
    body = "".join([
        sec("What maintenance does artificial turf need?",
            f"<p>Artificial turf needs a hose rinse every week or two, power brooming a few times a year to lift matted pile, and a deeper sanitizing clean twice a year timed around Central Florida's live oak leaf drop and rainy season. Storms and heavy pollen weeks call for an extra pass in between. None of it involves an in-ground sprinkler; {src('dep-rule', 'the state synthetic turf rule')} doesn't allow one to water turf at all.</p>"
            + table("Artificial turf maintenance calendar for Central Florida", ["Frequency", "Task", "Why it matters here"], cal_rows,
                    f"Live oak timing from {ext(IFAS_LIVEOAK, 'UF/IFAS live oak information')}; lovebug seasons from {ext(IFAS_LOVEBUGS, 'UF/IFAS Extension on lovebugs')}.")),
        photo("rooftop-amenity-deck", "Leaf litter on a rooftop turf deck after a windy day. A blower or a power broom clears this before it breaks down into the infill."),
        sec("How often should pet turf be cleaned?",
            f"<p>Dog turf needs a hose rinse most days at the spot a dog actually uses, and at least once a week across the whole run, because Central Florida heat turns bacteria in urine into odor within hours. Beyond that, plan on a professional deep clean with an enzyme or antimicrobial treatment every three to four months, sooner with more than one dog or a yard that stays shaded and damp.</p>"
            + f"<p>{svc('pet', 'Pet turf systems')} built with a fully permeable backing and zeolite or an antimicrobial-coated sand hold up longer between professional visits than regular lawn turf pressed into service as a dog run. {post('how-to-get-dog-urine-smell-out-of-artificial-turf', 'This guide')} covers what to try if odor has already set in.</p>"),
        sec("Who needs a professional visit, and who just needs a hose",
            "<p>An artificial turf cleaning service covers pet odor removal, turf deodorizing, power brooming, an infill top-up, turf sanitizing, and an enzyme cleaner worked into the backing where plain water doesn't reach. A homeowner's own rinse-and-broom routine covers most yards for the first year or two: hose it down, brush the high-traffic path, blow off leaves before they break down into the infill. A professional visit earns its cost once infill has visibly thinned, pet odor survives a normal rinse, or the pile in a traffic lane has matted down and stopped standing back up on its own.</p>"
            + f"<p>{svc('str', 'Vacation rentals')} are the other common case: a cleaning pass between a heavy booking stretch keeps the yard looking like the listing photos without the owner managing it long-distance. It's not worth booking a professional clean for turf under a year old with no pets and no visible problem; that money is better spent on nothing at all until there's something to actually fix.</p>"),
        sec("What a cleaning visit actually does",
            "<p>Here's the sequence on a standard visit, start to finish.</p>"
            + steps([("Walk the yard first.", "Check for matting, staining, low spots holding water, and any seam or edge that needs a separate repair call before cleaning goes ahead of it."),
                     ("Clear debris before water touches it.", "Leaves, acorns and lovebug residue get raked or blown off dry; wetting them first just presses them into the infill."),
                     ("Power broom against the grain.", "Lifts flattened pile and works old, compacted infill loose so it can be topped up evenly instead of layered over."),
                     ("Treat odor at the source.", "An enzyme or antimicrobial solution goes down into the infill and backing, not just across the top of the blades."),
                     ("Top up infill to depth.", "Brought back to roughly the original one to two pounds per square foot rather than left thin where it's washed or blown away."),
                     ("Final hose rinse and brush.", "A steady hose, not a high-pressure wand aimed to blast a section clean, which can strip infill and fray blade tips.")])),
        sec("What turf cleaning costs",
            f"<p>Published 2026 market ranges put a basic maintenance visit, rinse, debris removal and a power brooming, at $80 to $150 ({ext(SPARKLYTURF_CLEAN, 'a national cleaning-cost survey')}). A standard deep clean with infill work runs $150 to $400, and most homes land between $200 and $350. Pet-odor and sanitizing treatments sit toward the top of that range, because the enzyme product and the labor to work it into the infill cost more than a plain rinse.</p>"
            + table("Turf cleaning cost by service type (published market ranges)",
                    ["Service", "Market range", "What's included"],
                    [["Basic maintenance rinse and broom", "$80–$150 per visit", f"Debris removal, hose rinse, power broom ({ext(SPARKLYTURF_CLEAN, 'Sparkly Turf, 2026')})"],
                     ["Standard deep clean", "$150–$400, most homes $200–$350", "Deeper power brooming, infill top-up, spot treatment on stains"],
                     ["Pet-odor or sanitizing treatment", "Toward the top of the deep-clean range", "Enzyme or antimicrobial solution worked into the infill, sometimes a partial infill exchange"]])
            + f"<p>None of that is a Kissimmee-specific number; we haven't found a published Central Florida survey for turf cleaning as of {PRICE_DATE}, so a firm price follows a look at the yard's size and condition, the same as {svc('repair', 'a repair quote')}.</p>"),
        sec("Heat, pollen and lovebugs: cleaning turf through a Central Florida year",
            f"<p>Heat is why pet odor here needs more attention than the same yard would in a cooler climate; warmth speeds up the bacteria that turn urine into smell, so a rinse schedule that works up north isn't enough in Kissimmee. Live oaks drop their old leaves as new growth comes in, typically late winter into early spring ({ext(IFAS_LIVEOAK, 'UF/IFAS live oak information')}), and the tannins in a pile of wet oak leaves can stain turf fiber if they sit through a few afternoon storms. Florida runs two lovebug swarms a year, spring and again in late summer ({ext(IFAS_LOVEBUGS, 'UF/IFAS Extension on lovebugs')}), and their residue is acidic enough to dull turf color if it bakes in the sun instead of getting rinsed off within a day or two.</p>"
            + "<p>Rainy season, June through September, does some of the cleaning for free by washing dust and pollen off the blades, but it also carries loose debris into low spots where Kissimmee's sandy base has settled, so those spots need an extra pass after a heavy storm.</p>"),
        sec("Does cleaning affect drainage rules?",
            f"<p>Florida's synthetic turf standard requires an installed lawn to stay permeable and not increase runoff onto a neighbor's property ({src('marathon-pr', 'a summary of the state standard')}). Infill packed solid with years of dust, pollen and pet waste can slow how fast water actually gets through the backing, even though the product itself is still rated for the same drainage. Regular power brooming and an infill top-up are what keep the real-world drainage close to the rated {src('sgw-faq', 'manufacturer specification of more than 30 inches an hour')}, which matters most on lots near a pond or swale, where the state standard already limits how close turf can sit to the water.</p>"),
        sec("What a rushed cleaning job misses",
            "<p>A pressure washer aimed at the turf instead of a hose is the most common shortcut, and it can blow infill out of a section, fray blade tips, and on an older lawn loosen a seam that a gentler rinse would have left alone. Skipping the debris pass and going straight to water just presses leaves and lovebug residue deeper into the pile instead of removing them.</p>"
            + "<p>Spraying a deodorizer on top of the blades without working it into the infill treats the smell for a few days and misses where the odor actually comes from. And a clean that skips the infill top-up leaves the backing exposed in traffic lanes, which shows up as a dull, thin-looking stripe within a season.</p>"),
        sec("Between visits",
            f"<p>Rinse pet areas with a hose a few times a week between professional visits, more often at the peak of a Florida summer. Brush high-traffic paths against the grain every month or two so the pile keeps standing up on its own. Rake or blow off leaves and lovebug residue within a day or two rather than letting an afternoon storm work them into the infill. {post('oak-leaves-and-debris-on-artificial-turf', 'This guide')} covers debris season in more detail. If a spot keeps re-staining or smelling no matter how often it's rinsed, that's usually a sign for {svc('repair', 'a repair visit')} rather than another cleaning.</p>"),
        sec("How do you find the best turf cleaning company near me?",
            "<p>Ask what's actually included: a rinse and a broom is not the same service as an enzyme treatment worked into the infill, and the price should say which one you're getting. Ask whether infill gets topped up as part of the visit or billed separately, since a clean that leaves infill thin looks worse within weeks. And ask how they handle water pressure; a company that can't explain why it uses a hose instead of a pressure washer probably hasn't thought about what a blast of water does to years-old backing.</p>"
            + cta("Get a cleaning quote", "Tell us the yard size, whether pets use it, and when it was last cleaned, and we'll quote the visit.")),
    ])
    faqs = [
        faq("How long after a cleaning visit can pets or kids use the yard again?", "Usually right away for a basic rinse and broom. If an enzyme or sanitizing treatment was applied, give it fifteen to twenty minutes to sit before heavy use, and a bit longer in shade where things dry more slowly."),
        faq("Does turf cleaning remove old pet odor completely?", "Often, if the odor is in the infill and hasn't reached the backing or the base underneath. Odor that survives a proper deep clean and a fresh infill swap usually means urine has worked past the infill, which points toward replacement rather than another cleaning."),
        faq("Can I clean artificial turf myself between professional visits?", "Yes, and it's the better routine. A hose rinse, a stiff push broom used against the grain, and prompt removal of leaves and debris cover most of what turf needs between the twice-yearly deep cleans."),
        faq("What's the difference between power brooming and brushing?", "Power brooming uses a machine, usually a walk-behind unit with rotating bristles, to lift matted pile and loosen packed infill across a large area quickly. Hand brushing with a stiff broom does the same job on a smaller scale or in tight corners a machine can't reach."),
        faq("Do you top up infill during a regular cleaning visit?", "Yes, when it's visibly thin. Infill migrates and compacts over time from rinsing, rain and foot traffic, and a clean that only rinses and broomes without restoring the depth leaves the backing more exposed than before."),
        faq("How soon after a storm should turf be cleaned?", "Within a few days if debris or standing water is visible. Leaves and organic matter left wet against the blades start to break down and stain the fiber faster in Florida heat than they would in a cooler climate."),
        faq("Will cleaning turf void a warranty from the original installer?", "A hose rinse and gentle power brooming shouldn't affect a manufacturer's warranty; those cover UV fade and material defects, not maintenance. A pressure washer or harsh chemical could, so ask the original installer what the warranty language actually excludes before using either."),
    ]
    return page("/turf-cleaning/", "service",
                "Artificial Turf Cleaning Service in Kissimmee, FL",
                "Artificial turf cleaning service in Kissimmee: a Central Florida maintenance calendar, pet-odor removal and 2026 market-range pricing for power brooming.",
                "Artificial turf cleaning service in Kissimmee, Florida",
                capsule("An artificial turf cleaning service rinses, power brooms and deodorizes turf so it drains, smells and looks the way it did on installation day. In Kissimmee, a basic visit runs roughly $80 to $150 and a deep clean with pet-odor treatment runs $150 to $400, based on published 2026 market ranges. Central Florida's oak leaf drop, pollen and lovebug seasons all shape the schedule."),
                body, faqs=faqs, service="cleaning", image="rooftop-amenity-deck", crumbs=[("Services", "/services/")], crumb="Turf cleaning",
                sources=["dep-rule", "marathon-pr", "sgw-faq",
                         ("Sparkly Turf — artificial grass cleaning cost, 2026", SPARKLYTURF_CLEAN),
                         ("UF/IFAS Sarasota County Extension — lovebugs, the bug we love to hate", IFAS_LOVEBUGS),
                         ("UF/IFAS North Florida REC — live oak information", IFAS_LIVEOAK)],
                related=[("/pet-turf/", "Pet turf built to be rinsed"), ("/turf-repair/", "When cleaning isn't enough"),
                         ("/blog/how-to-get-dog-urine-smell-out-of-artificial-turf/", "Getting dog odor out of turf"),
                         ("/blog/oak-leaves-and-debris-on-artificial-turf/", "Oak leaves and debris on turf"),
                         ("/compare/zeolite-vs-silica-vs-antimicrobial-infill/", "Infill compared for odor control"),
                         ("/artificial-turf-cost/", "Full turf cost guide")])


# ---------------------------------------------------------------- 4. turf replacement
def replacement_page():
    diag_rows = [
        ["A single open seam or a small burn patch", "Yes", "Not necessary", "Isolated failure; the rest of the base and turf are still sound"],
        ["Widespread fading and brittle blades across the whole lawn", "No, a patch won't match", "Yes", "The fiber itself has UV-degraded; that doesn't repair, it only gets replaced"],
        ["Multiple soft, sunken or spongy spots at 12+ years old", "Rarely worth it", "Usually", "The base has likely failed in more than one place, not only where it shows"],
        ["Pet odor that survives a deep clean and fresh infill", "No", "Yes", "Often means the backing or an old fabric weed barrier underneath is holding urine"],
        ["Turf installed before the 2026 state standard, irrigation still capped underneath", "N/A", "Worth doing at the same time", "Replacement is the practical moment to remove old heads and anchor edges to the current rule"],
    ]
    body = "".join([
        sec("Repair or replace? What the base tells you",
            f"<p>Artificial turf replacement means old turf removal, a base rebuild where it's needed, honest turf disposal, and a re-turf that upgrades the product you had rather than a like-for-like swap. The condition of what's underneath, not just how the lawn looks, is what should decide between a {svc('repair', 'repair')} and a full replacement.</p>"
            + table("Repair or replace: reading the signs", ["What you see", "Repair candidate", "Replace candidate", "Why"], diag_rows)),
        sec("What survives a replacement, and what doesn't",
            "<p>A base that's still flat, well-drained and at the right depth doesn't need to be dug out and redone; that's the single biggest cost difference between a replacement and a first-time install. We probe it in a few spots, check for soft or wet areas, and reuse what's still doing its job while adding and recompacting where it's thinned. Edging often survives too. A bender-board or paver border holds up longer than the turf inside it, so a still-solid edge gets reused rather than pulled for no reason.</p>"
            + f"<p>What doesn't survive: the turf itself, obviously, along with any fabric weed barrier from an older pet install, since that's usually the thing holding years of urine odor. Old irrigation heads that were simply capped rather than removed get addressed properly this time, since the current standard doesn't allow an in-ground system to water turf at all. Infill is the other thing worth checking before assuming it can stay: {src('dep-rule', 'the current state standard')} only allows crumb rubber or another synthetic infill inside the footprint of playground equipment, so an older lawn or general play area filled with rubber or TPE gets refilled with clean silica sand, zeolite or a coated sand during the replacement.</p>"),
        sec("Ten to fifteen years of Florida sun, up close",
            f"<p>Turf in Florida generally lasts ten to twenty years depending on UV stabilization, traffic and infill ({src('stn-life', 'industry lifespan data')}), and the low end of that range is common on unshaded Central Florida lawns that see full sun most of the year. What worn-out looks like by then: blades gone from green to a washed-out gray-green, brittle rather than springy underfoot; infill migrated or compacted so the backing shows through in traffic lanes; a surface that's stopped bouncing back after someone walks across it.</p>"
            + f"<p>A lawn that hit those marks five years ago and is only now getting replaced usually has base problems layered on top of the fiber problems, part of why the quote is rarely just the cost of new material. {post('how-long-does-artificial-turf-last-in-florida', 'This guide')} breaks lifespan down by use and product.</p>"),
        sec("How a replacement job runs",
            "<p>The sequence differs from a first-time install mainly in the first step.</p>"
            + steps([("We evaluate what's underneath first.", "Pull back a corner, probe the base for depth and moisture, and decide how much of it is worth keeping before pricing anything."),
                     ("Old turf comes out.", "Cut into sections, rolled, and hauled off; a large yard can mean several thousand pounds of material leaving the site."),
                     ("The base gets corrected, not just reused blindly.", "Low spots are regraded, thinned base gets built back up, and the whole area is recompacted in lifts even where most of it stayed."),
                     ("New turf goes in to the current standard.", "A product with no intentionally added PFAS or heavy metals, edges and seams anchored the way Rule 62-308.100 requires."),
                     ("Irrigation is capped properly.", "Any head that survived the old install, even one that was already turned off, gets capped at the line rather than left in place."),
                     ("Final grade and drainage check.", "We confirm the 1 to 2 percent slope away from the house still holds before the last section of turf goes down.")])),
        sec("What artificial turf replacement costs",
            f"<p>Artificial turf replacement is quoted per job rather than off a fixed rate, but it prices closer to a first-time install than to a repair, because most of the labor, demo, base work, new turf, repeats either way. A full tear-out and rebuild often lands near the lower-to-middle part of the usual Central Florida installed range, roughly {price('residential')} a square foot, and a base that only needs light correction can trim a meaningful share off that.</p>"
            + "<p>What raises it: hauling a large volume of old turf and infill off site, a base that failed in more than one area, and capping or rerouting irrigation left in place under the old lawn. What lowers it: a base that's still flat and draining, sound edging that doesn't need to be pulled, and a straightforward rectangular yard.</p>"),
        sec("Where the old turf actually goes",
            f"<p>Turf is technically recyclable; plastics can be separated, melted and repelletized. In practice, most residential turf in Florida is hauled to a landfill or a construction-and-demolition debris facility, the same as old carpet, because separating fiber, backing and infill takes equipment most local waste operations don't run ({ext(WASTEADV_RECYCLE, 'an industry overview of turf recycling')}). We haven't found a synthetic-turf recycling program serving Central Florida as of {PRICE_DATE}. Landfilling isn't an oversight the state rule ignores, either: {src('dep-rule', 'Rule 62-308.100')} requires turf, backing and infill to be disposable at a Florida-permitted landfill under normal conditions, which is exactly where most of it ends up. Disposal is typically priced by weight; national guides put it around $60 to $70 a ton ({ext(TOTALTURF_DISPOSAL, 'a synthetic grass disposal guide')}), and a mid-size residential lawn's worth of old turf and infill adds up to a real number, part of a replacement quote rather than an afterthought.</p>"),
        sec("Bringing an older install up to the current rule",
            f"<p>A lot of turf around Kissimmee went in before Florida adopted Rule 62-308.100 on May 19, 2026, the first statewide minimum standard for synthetic turf on single-family lots ({src('dep-rule', 'Rule 62-308.100')}). Replacement is the natural moment to catch an older lawn up: a product with no intentionally added PFAS or heavy metals, a washed and open-graded base instead of whatever was under the original install, edges and seams anchored to handle wind and flooding, and irrigation heads capped rather than left running under the turf. If the old install sits inside a live oak's drip line, or closer than ten feet to a pond or canal without a seawall or bulkhead between them, replacement is also the moment to correct that footprint instead of repeating it. On a Poinciana or Harmony lot with a septic system, we also confirm the new layout leaves the tank's lid reachable for pump-out, easy to overlook on an install built before the rule existed.</p>"
            + "<p>None of this requires a new permit from the state. Rule 62-308.100 sets a material and installation standard, and it says outright that it creates no new department-issued permit and doesn't touch easements or rights-of-way; what changed is what a compliant lawn has to look like, not who has to sign off on it.</p>"),
        sec("HOA paperwork the second time around",
            f"<p>An HOA that approved the original install years ago may still want to see the new one, especially if the community's design guidelines changed in the meantime or the visible footprint is different. {a('/laws/hoa-rules/', 'What a Florida HOA can and can not restrict')} explains that a fenced backyard is generally protected from that review under F.S. 720.3045, while a front yard isn't. We prepare a fresh sample, spec sheet and site plan for the file when a community asks for one, same as on a first-time install.</p>"),
        sec("What a bad replacement job looks like",
            "<p>The most common shortcut is skipping the base evaluation entirely and laying new turf over whatever's there, wet spots, soft spots and all, so the new lawn inherits the old lawn's problems on day one. Reusing edging that's already failed, cracked bender board, a paver border that's settled, saves a little money and costs more within a year when the new turf's edge lifts along it. Leaving old irrigation lines simply capped with tape instead of properly plugged is a leak waiting for the first hard rain to find it.</p>"),
        sec("After the new turf goes down",
            "<p>Treat a replacement's first few months like a new install: keep heavy furniture off it while the base settles, rinse and brush on the same schedule as before, and walk the perimeter after the first real storm to check that every edge and seam is holding. Keep the product's spec sheet and the invoice describing the base work done; useful if an HOA ever asks again, and useful to us if a question comes up later about what's under the new lawn.</p>"),
        sec("Who is the best artificial turf replacement company near me?",
            "<p>Ask to see the base before it's covered; a contractor confident in the work will show you the compacted material and the grade before the last roll of turf goes down. Ask what happens to the old turf and whether disposal is itemized in the quote. And ask directly whether the new install will meet the current state standard, anchored edges, capped irrigation, a PFAS-free product, since that's a fair baseline for anyone replacing turf in Florida now, not an upsell.</p>"
            + cta("Get a replacement quote", "We'll look at what's underneath before pricing anything, and tell you honestly if a repair would do instead.")),
    ])
    faqs = [
        faq("How do I know if my base needs to be rebuilt or just corrected?", "We probe it in several spots with a rod or a shovel. Firm, dry material that hasn't shifted usually just needs recompacting; soft, wet or spongy material in more than one spot means the base itself has failed and needs to come out and be rebuilt."),
        faq("Can the old turf be reused anywhere, like a dog run or a shed pad?", "Rarely for anything load-bearing or visible; UV-degraded fiber is brittle and the backing is usually near the end of its life too. It occasionally works as a temporary weed barrier under mulch, but that's a stretch, not a real second life."),
        faq("Does replacement turf need a permit if the original install didn't?", "Usually not a building permit, since it's the same use of the lot, but check with your city or county if the project also changes grading or drainage. An HOA that reviewed the first install may want to see the new one even without a government permit involved."),
        faq("How long does a typical replacement take?", "Two to five days for a residential yard, depending on how much of the base needs correcting. A yard where the base only needs light recompaction moves closer to a first-time install's timeline; one needing a full rebuild takes longer."),
        faq("Will a replacement match the rest of my landscaping if only part of the yard is worn out?", "We can often match pile height and color family to an adjoining area that's staying, though turf from a different production run is never a perfect color match. Full-yard replacement avoids the mismatch question entirely."),
        faq("Is it cheaper to replace turf myself and just hire out disposal?", "Removing the old turf yourself can trim some labor cost, but the base correction underneath is the part that determines how the new lawn performs, and that's harder to get right without the equipment and experience to grade and compact it properly."),
        faq("Does homeowners insurance ever cover turf replacement?", "Sometimes, for storm or fire damage specifically, rarely for ordinary wear from age and sun. Check your policy's language on landscaping or outdoor improvements before assuming either way, and keep the original install invoice in case a claim needs it."),
    ]
    return page("/turf-replacement/", "service",
                "Artificial Turf Replacement in Kissimmee, FL",
                "Artificial turf replacement in Kissimmee: repair-vs-replace signs, what gets reused, Florida disposal reality, and updating an old lawn to the 2026 turf rule.",
                "Artificial turf replacement in Kissimmee, Florida",
                capsule("Artificial turf replacement means pulling out a worn-out lawn, correcting the base underneath it, and laying a new surface, usually once a lawn is ten to fifteen years into Florida's sun. A full tear-out and rebuild prices close to a new install; a sound base that only needs the old turf removed trims a meaningful share off that. Most jobs also bring an older install up to the current state turf standard."),
                body, faqs=faqs, service="replacement", crumbs=[("Services", "/services/")], crumb="Turf replacement",
                sources=["dep-rule", "marathon-pr", "fs7203045", "stn-life", "attampa-cost",
                         ("Total Turf Supply — how to properly dispose of synthetic grass", TOTALTURF_DISPOSAL),
                         ("Waste Advantage Magazine — ways you can recycle artificial turf", WASTEADV_RECYCLE)],
                related=[("/turf-repair/", "Repairing turf instead of replacing it"), ("/turf-cleaning/", "A deep clean before deciding"),
                         ("/blog/how-long-does-artificial-turf-last-in-florida/", "How long turf lasts in Florida"),
                         ("/blog/is-artificial-turf-bad-for-the-environment/", "Is artificial turf bad for the environment?"),
                         ("/blog/base-under-artificial-turf-florida-sandy-soil/", "What goes under turf on Florida sand"),
                         ("/artificial-turf-cost/", "Full turf cost guide")])


def get_pages():
    pages = [pavers_page(), repair_page(), cleaning_page(), replacement_page()]
    for p in pages:
        p["body"] = p["body"] + "<!--AUTO:service-cities-->"
    return pages
